version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  skip-dirs:
    - internal/db/sqlc

linters:
  enable:
    - govet
    - staticcheck
    - unused
    - ineffassign
  disable:
    # TODO: Fix these and re-enable
    - errcheck  # Many unchecked errors in codebase, fix incrementally
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow

formatters:
  enable:
    - gofmt
