version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - unused
    - ineffassign
  settings:
    govet:
      disable:
        - fieldalignment
        - shadow

formatters:
  enable:
    - gofmt

output:
  formats:
    text:
      path: stdout
