// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package sqlc

import (
	"context"
	"database/sql"
)

const CreateAgent = `-- name: CreateAgent :one
INSERT INTO agents (name, project_key, current_session_id, created_at, last_active_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, project_key, current_session_id, created_at, last_active_at
`

type CreateAgentParams struct {
	Name             string
	ProjectKey       sql.NullString
	CurrentSessionID sql.NullString
	CreatedAt        int64
	LastActiveAt     int64
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, CreateAgent,
		arg.Name,
		arg.ProjectKey,
		arg.CurrentSessionID,
		arg.CreatedAt,
		arg.LastActiveAt,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectKey,
		&i.CurrentSessionID,
		&i.CreatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const CreateSessionIdentity = `-- name: CreateSessionIdentity :exec
INSERT INTO session_identities (session_id, agent_id, project_key, created_at, last_active_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (session_id) DO UPDATE SET
    agent_id = excluded.agent_id,
    project_key = excluded.project_key,
    last_active_at = excluded.last_active_at
`

type CreateSessionIdentityParams struct {
	SessionID    string
	AgentID      int64
	ProjectKey   sql.NullString
	CreatedAt    int64
	LastActiveAt int64
}

func (q *Queries) CreateSessionIdentity(ctx context.Context, arg CreateSessionIdentityParams) error {
	_, err := q.db.ExecContext(ctx, CreateSessionIdentity,
		arg.SessionID,
		arg.AgentID,
		arg.ProjectKey,
		arg.CreatedAt,
		arg.LastActiveAt,
	)
	return err
}

const DeleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents WHERE id = ?
`

func (q *Queries) DeleteAgent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeleteAgent, id)
	return err
}

const DeleteSessionIdentity = `-- name: DeleteSessionIdentity :exec
DELETE FROM session_identities WHERE session_id = ?
`

func (q *Queries) DeleteSessionIdentity(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, DeleteSessionIdentity, sessionID)
	return err
}

const GetAgent = `-- name: GetAgent :one
SELECT id, name, project_key, current_session_id, created_at, last_active_at FROM agents WHERE id = ?
`

func (q *Queries) GetAgent(ctx context.Context, id int64) (Agent, error) {
	row := q.db.QueryRowContext(ctx, GetAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectKey,
		&i.CurrentSessionID,
		&i.CreatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const GetAgentByName = `-- name: GetAgentByName :one
SELECT id, name, project_key, current_session_id, created_at, last_active_at FROM agents WHERE name = ?
`

func (q *Queries) GetAgentByName(ctx context.Context, name string) (Agent, error) {
	row := q.db.QueryRowContext(ctx, GetAgentByName, name)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectKey,
		&i.CurrentSessionID,
		&i.CreatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const GetAgentBySessionID = `-- name: GetAgentBySessionID :one
SELECT a.id, a.name, a.project_key, a.current_session_id, a.created_at, a.last_active_at FROM agents a
JOIN session_identities si ON a.id = si.agent_id
WHERE si.session_id = ?
`

func (q *Queries) GetAgentBySessionID(ctx context.Context, sessionID string) (Agent, error) {
	row := q.db.QueryRowContext(ctx, GetAgentBySessionID, sessionID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectKey,
		&i.CurrentSessionID,
		&i.CreatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const GetSessionIdentity = `-- name: GetSessionIdentity :one
SELECT session_id, agent_id, project_key, created_at, last_active_at FROM session_identities WHERE session_id = ?
`

func (q *Queries) GetSessionIdentity(ctx context.Context, sessionID string) (SessionIdentity, error) {
	row := q.db.QueryRowContext(ctx, GetSessionIdentity, sessionID)
	var i SessionIdentity
	err := row.Scan(
		&i.SessionID,
		&i.AgentID,
		&i.ProjectKey,
		&i.CreatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const GetSessionIdentityByProject = `-- name: GetSessionIdentityByProject :one
SELECT session_id, agent_id, project_key, created_at, last_active_at FROM session_identities WHERE project_key = ? ORDER BY last_active_at DESC LIMIT 1
`

func (q *Queries) GetSessionIdentityByProject(ctx context.Context, projectKey sql.NullString) (SessionIdentity, error) {
	row := q.db.QueryRowContext(ctx, GetSessionIdentityByProject, projectKey)
	var i SessionIdentity
	err := row.Scan(
		&i.SessionID,
		&i.AgentID,
		&i.ProjectKey,
		&i.CreatedAt,
		&i.LastActiveAt,
	)
	return i, err
}

const ListAgents = `-- name: ListAgents :many
SELECT id, name, project_key, current_session_id, created_at, last_active_at FROM agents ORDER BY last_active_at DESC
`

func (q *Queries) ListAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, ListAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProjectKey,
			&i.CurrentSessionID,
			&i.CreatedAt,
			&i.LastActiveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAgentsByProject = `-- name: ListAgentsByProject :many
SELECT id, name, project_key, current_session_id, created_at, last_active_at FROM agents WHERE project_key = ? ORDER BY last_active_at DESC
`

func (q *Queries) ListAgentsByProject(ctx context.Context, projectKey sql.NullString) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, ListAgentsByProject, projectKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProjectKey,
			&i.CurrentSessionID,
			&i.CreatedAt,
			&i.LastActiveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListSessionIdentitiesByAgent = `-- name: ListSessionIdentitiesByAgent :many
SELECT session_id, agent_id, project_key, created_at, last_active_at FROM session_identities WHERE agent_id = ? ORDER BY last_active_at DESC
`

func (q *Queries) ListSessionIdentitiesByAgent(ctx context.Context, agentID int64) ([]SessionIdentity, error) {
	rows, err := q.db.QueryContext(ctx, ListSessionIdentitiesByAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionIdentity
	for rows.Next() {
		var i SessionIdentity
		if err := rows.Scan(
			&i.SessionID,
			&i.AgentID,
			&i.ProjectKey,
			&i.CreatedAt,
			&i.LastActiveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateAgentLastActive = `-- name: UpdateAgentLastActive :exec
UPDATE agents SET last_active_at = ? WHERE id = ?
`

type UpdateAgentLastActiveParams struct {
	LastActiveAt int64
	ID           int64
}

func (q *Queries) UpdateAgentLastActive(ctx context.Context, arg UpdateAgentLastActiveParams) error {
	_, err := q.db.ExecContext(ctx, UpdateAgentLastActive, arg.LastActiveAt, arg.ID)
	return err
}

const UpdateAgentSession = `-- name: UpdateAgentSession :exec
UPDATE agents SET current_session_id = ?, last_active_at = ? WHERE id = ?
`

type UpdateAgentSessionParams struct {
	CurrentSessionID sql.NullString
	LastActiveAt     int64
	ID               int64
}

func (q *Queries) UpdateAgentSession(ctx context.Context, arg UpdateAgentSessionParams) error {
	_, err := q.db.ExecContext(ctx, UpdateAgentSession, arg.CurrentSessionID, arg.LastActiveAt, arg.ID)
	return err
}

const UpdateSessionIdentityLastActive = `-- name: UpdateSessionIdentityLastActive :exec
UPDATE session_identities SET last_active_at = ? WHERE session_id = ?
`

type UpdateSessionIdentityLastActiveParams struct {
	LastActiveAt int64
	SessionID    string
}

func (q *Queries) UpdateSessionIdentityLastActive(ctx context.Context, arg UpdateSessionIdentityLastActiveParams) error {
	_, err := q.db.ExecContext(ctx, UpdateSessionIdentityLastActive, arg.LastActiveAt, arg.SessionID)
	return err
}
