// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: annotations.sql

package sqlc

import (
	"context"
	"database/sql"
)

const CreateDiffAnnotation = `-- name: CreateDiffAnnotation :one
INSERT INTO diff_annotations (
    annotation_id, message_id, annotation_type, scope,
    file_path, line_start, line_end, side,
    text, suggested_code, original_code,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, annotation_id, message_id, annotation_type, scope, file_path, line_start, line_end, side, text, suggested_code, original_code, created_by, created_at, updated_at
`

type CreateDiffAnnotationParams struct {
	AnnotationID   string
	MessageID      int64
	AnnotationType string
	Scope          string
	FilePath       string
	LineStart      int64
	LineEnd        int64
	Side           string
	Text           sql.NullString
	SuggestedCode  sql.NullString
	OriginalCode   sql.NullString
	CreatedAt      int64
	UpdatedAt      int64
}

func (q *Queries) CreateDiffAnnotation(ctx context.Context, arg CreateDiffAnnotationParams) (DiffAnnotation, error) {
	row := q.db.QueryRowContext(ctx, CreateDiffAnnotation,
		arg.AnnotationID,
		arg.MessageID,
		arg.AnnotationType,
		arg.Scope,
		arg.FilePath,
		arg.LineStart,
		arg.LineEnd,
		arg.Side,
		arg.Text,
		arg.SuggestedCode,
		arg.OriginalCode,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i DiffAnnotation
	err := row.Scan(
		&i.ID,
		&i.AnnotationID,
		&i.MessageID,
		&i.AnnotationType,
		&i.Scope,
		&i.FilePath,
		&i.LineStart,
		&i.LineEnd,
		&i.Side,
		&i.Text,
		&i.SuggestedCode,
		&i.OriginalCode,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const CreatePlanAnnotation = `-- name: CreatePlanAnnotation :one
INSERT INTO plan_annotations (
    plan_review_id, annotation_id, block_id, annotation_type,
    text, original_text, start_offset, end_offset,
    diff_context, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, plan_review_id, annotation_id, block_id, annotation_type, text, original_text, start_offset, end_offset, diff_context, created_by, created_at, updated_at
`

type CreatePlanAnnotationParams struct {
	PlanReviewID   string
	AnnotationID   string
	BlockID        string
	AnnotationType string
	Text           sql.NullString
	OriginalText   string
	StartOffset    int64
	EndOffset      int64
	DiffContext    sql.NullString
	CreatedAt      int64
	UpdatedAt      int64
}

func (q *Queries) CreatePlanAnnotation(ctx context.Context, arg CreatePlanAnnotationParams) (PlanAnnotation, error) {
	row := q.db.QueryRowContext(ctx, CreatePlanAnnotation,
		arg.PlanReviewID,
		arg.AnnotationID,
		arg.BlockID,
		arg.AnnotationType,
		arg.Text,
		arg.OriginalText,
		arg.StartOffset,
		arg.EndOffset,
		arg.DiffContext,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i PlanAnnotation
	err := row.Scan(
		&i.ID,
		&i.PlanReviewID,
		&i.AnnotationID,
		&i.BlockID,
		&i.AnnotationType,
		&i.Text,
		&i.OriginalText,
		&i.StartOffset,
		&i.EndOffset,
		&i.DiffContext,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteDiffAnnotation = `-- name: DeleteDiffAnnotation :exec
DELETE FROM diff_annotations WHERE annotation_id = ?
`

func (q *Queries) DeleteDiffAnnotation(ctx context.Context, annotationID string) error {
	_, err := q.db.ExecContext(ctx, DeleteDiffAnnotation, annotationID)
	return err
}

const DeleteDiffAnnotationsByMessage = `-- name: DeleteDiffAnnotationsByMessage :exec
DELETE FROM diff_annotations WHERE message_id = ?
`

func (q *Queries) DeleteDiffAnnotationsByMessage(ctx context.Context, messageID int64) error {
	_, err := q.db.ExecContext(ctx, DeleteDiffAnnotationsByMessage, messageID)
	return err
}

const DeletePlanAnnotation = `-- name: DeletePlanAnnotation :exec
DELETE FROM plan_annotations WHERE annotation_id = ?
`

func (q *Queries) DeletePlanAnnotation(ctx context.Context, annotationID string) error {
	_, err := q.db.ExecContext(ctx, DeletePlanAnnotation, annotationID)
	return err
}

const DeletePlanAnnotationsByReview = `-- name: DeletePlanAnnotationsByReview :exec
DELETE FROM plan_annotations WHERE plan_review_id = ?
`

func (q *Queries) DeletePlanAnnotationsByReview(ctx context.Context, planReviewID string) error {
	_, err := q.db.ExecContext(ctx, DeletePlanAnnotationsByReview, planReviewID)
	return err
}

const GetDiffAnnotation = `-- name: GetDiffAnnotation :one
SELECT id, annotation_id, message_id, annotation_type, scope, file_path, line_start, line_end, side, text, suggested_code, original_code, created_by, created_at, updated_at FROM diff_annotations WHERE annotation_id = ?
`

func (q *Queries) GetDiffAnnotation(ctx context.Context, annotationID string) (DiffAnnotation, error) {
	row := q.db.QueryRowContext(ctx, GetDiffAnnotation, annotationID)
	var i DiffAnnotation
	err := row.Scan(
		&i.ID,
		&i.AnnotationID,
		&i.MessageID,
		&i.AnnotationType,
		&i.Scope,
		&i.FilePath,
		&i.LineStart,
		&i.LineEnd,
		&i.Side,
		&i.Text,
		&i.SuggestedCode,
		&i.OriginalCode,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetPlanAnnotation = `-- name: GetPlanAnnotation :one
SELECT id, plan_review_id, annotation_id, block_id, annotation_type, text, original_text, start_offset, end_offset, diff_context, created_by, created_at, updated_at FROM plan_annotations WHERE annotation_id = ?
`

func (q *Queries) GetPlanAnnotation(ctx context.Context, annotationID string) (PlanAnnotation, error) {
	row := q.db.QueryRowContext(ctx, GetPlanAnnotation, annotationID)
	var i PlanAnnotation
	err := row.Scan(
		&i.ID,
		&i.PlanReviewID,
		&i.AnnotationID,
		&i.BlockID,
		&i.AnnotationType,
		&i.Text,
		&i.OriginalText,
		&i.StartOffset,
		&i.EndOffset,
		&i.DiffContext,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ListDiffAnnotationsByMessage = `-- name: ListDiffAnnotationsByMessage :many
SELECT id, annotation_id, message_id, annotation_type, scope, file_path, line_start, line_end, side, text, suggested_code, original_code, created_by, created_at, updated_at FROM diff_annotations
WHERE message_id = ?
ORDER BY file_path ASC, line_start ASC
LIMIT 500
`

func (q *Queries) ListDiffAnnotationsByMessage(ctx context.Context, messageID int64) ([]DiffAnnotation, error) {
	rows, err := q.db.QueryContext(ctx, ListDiffAnnotationsByMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiffAnnotation
	for rows.Next() {
		var i DiffAnnotation
		if err := rows.Scan(
			&i.ID,
			&i.AnnotationID,
			&i.MessageID,
			&i.AnnotationType,
			&i.Scope,
			&i.FilePath,
			&i.LineStart,
			&i.LineEnd,
			&i.Side,
			&i.Text,
			&i.SuggestedCode,
			&i.OriginalCode,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListPlanAnnotationsByReview = `-- name: ListPlanAnnotationsByReview :many
SELECT id, plan_review_id, annotation_id, block_id, annotation_type, text, original_text, start_offset, end_offset, diff_context, created_by, created_at, updated_at FROM plan_annotations
WHERE plan_review_id = ?
ORDER BY id ASC
LIMIT 500
`

func (q *Queries) ListPlanAnnotationsByReview(ctx context.Context, planReviewID string) ([]PlanAnnotation, error) {
	rows, err := q.db.QueryContext(ctx, ListPlanAnnotationsByReview, planReviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlanAnnotation
	for rows.Next() {
		var i PlanAnnotation
		if err := rows.Scan(
			&i.ID,
			&i.PlanReviewID,
			&i.AnnotationID,
			&i.BlockID,
			&i.AnnotationType,
			&i.Text,
			&i.OriginalText,
			&i.StartOffset,
			&i.EndOffset,
			&i.DiffContext,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateDiffAnnotation = `-- name: UpdateDiffAnnotation :exec
UPDATE diff_annotations
SET text = ?, suggested_code = ?, original_code = ?, updated_at = ?
WHERE annotation_id = ?
`

type UpdateDiffAnnotationParams struct {
	Text          sql.NullString
	SuggestedCode sql.NullString
	OriginalCode  sql.NullString
	UpdatedAt     int64
	AnnotationID  string
}

func (q *Queries) UpdateDiffAnnotation(ctx context.Context, arg UpdateDiffAnnotationParams) error {
	_, err := q.db.ExecContext(ctx, UpdateDiffAnnotation,
		arg.Text,
		arg.SuggestedCode,
		arg.OriginalCode,
		arg.UpdatedAt,
		arg.AnnotationID,
	)
	return err
}

const UpdatePlanAnnotation = `-- name: UpdatePlanAnnotation :exec
UPDATE plan_annotations
SET text = ?, original_text = ?, start_offset = ?,
    end_offset = ?, diff_context = ?, updated_at = ?
WHERE annotation_id = ?
`

type UpdatePlanAnnotationParams struct {
	Text         sql.NullString
	OriginalText string
	StartOffset  int64
	EndOffset    int64
	DiffContext  sql.NullString
	UpdatedAt    int64
	AnnotationID string
}

func (q *Queries) UpdatePlanAnnotation(ctx context.Context, arg UpdatePlanAnnotationParams) error {
	_, err := q.db.ExecContext(ctx, UpdatePlanAnnotation,
		arg.Text,
		arg.OriginalText,
		arg.StartOffset,
		arg.EndOffset,
		arg.DiffContext,
		arg.UpdatedAt,
		arg.AnnotationID,
	)
	return err
}
