// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type Activity struct {
	ID           int64
	AgentID      int64
	ActivityType string
	Description  string
	Metadata     sql.NullString
	CreatedAt    int64
}

type Agent struct {
	ID               int64
	Name             string
	ProjectKey       sql.NullString
	GitBranch        sql.NullString
	CurrentSessionID sql.NullString
	CreatedAt        int64
	LastActiveAt     int64
}

type ConsumerOffset struct {
	AgentID    int64
	TopicID    int64
	LastOffset int64
	UpdatedAt  int64
}

type Message struct {
	ID          int64
	ThreadID    string
	TopicID     int64
	LogOffset   int64
	SenderID    int64
	Subject     string
	BodyMd      string
	Priority    string
	DeadlineAt  sql.NullInt64
	Attachments sql.NullString
	CreatedAt   int64
}

type MessageRecipient struct {
	MessageID    int64
	AgentID      int64
	State        string
	SnoozedUntil sql.NullInt64
	ReadAt       sql.NullInt64
	AckedAt      sql.NullInt64
}

type MessagesFt struct {
	Subject string
	BodyMd  string
}

type SessionIdentity struct {
	SessionID    string
	AgentID      int64
	ProjectKey   sql.NullString
	GitBranch    sql.NullString
	CreatedAt    int64
	LastActiveAt int64
}

type Subscription struct {
	ID           int64
	AgentID      int64
	TopicID      int64
	SubscribedAt int64
}

type Topic struct {
	ID               int64
	Name             string
	TopicType        string
	RetentionSeconds sql.NullInt64
	CreatedAt        int64
}
