// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type AgentSummary struct {
	ID             int64
	AgentID        int64
	Summary        string
	Delta          string
	TranscriptHash string
	CostUsd        float64
	CreatedAt      int64
}

type Activity struct {
	ID           int64
	AgentID      int64
	ActivityType string
	Description  string
	Metadata     sql.NullString
	CreatedAt    int64
}

type Agent struct {
	ID               int64
	Name             string
	ProjectKey       sql.NullString
	GitBranch        sql.NullString
	CurrentSessionID sql.NullString
	CreatedAt        int64
	LastActiveAt     int64
	Purpose          sql.NullString
	WorkingDir       sql.NullString
	Hostname         sql.NullString
}

type AgentTask struct {
	ID           int64
	AgentID      int64
	ListID       string
	ClaudeTaskID string
	Subject      string
	Description  sql.NullString
	ActiveForm   sql.NullString
	Metadata     sql.NullString
	Status       string
	Owner        sql.NullString
	BlockedBy    sql.NullString
	Blocks       sql.NullString
	CreatedAt    int64
	UpdatedAt    int64
	StartedAt    sql.NullInt64
	CompletedAt  sql.NullInt64
	FilePath     sql.NullString
	FileMtime    sql.NullInt64
}

type AvailableTask struct {
	ID           int64
	AgentID      int64
	ListID       string
	ClaudeTaskID string
	Subject      string
	Description  sql.NullString
	ActiveForm   sql.NullString
	Metadata     sql.NullString
	Status       string
	Owner        sql.NullString
	BlockedBy    sql.NullString
	Blocks       sql.NullString
	CreatedAt    int64
	UpdatedAt    int64
	StartedAt    sql.NullInt64
	CompletedAt  sql.NullInt64
	FilePath     sql.NullString
	FileMtime    sql.NullInt64
}

type ConsumerOffset struct {
	AgentID    int64
	TopicID    int64
	LastOffset int64
	UpdatedAt  int64
}

type Message struct {
	ID              int64
	ThreadID        string
	TopicID         int64
	LogOffset       int64
	SenderID        int64
	Subject         string
	BodyMd          string
	Priority        string
	DeadlineAt      sql.NullInt64
	Attachments     sql.NullString
	CreatedAt       int64
	DeletedBySender int64
	Metadata        sql.NullString
	IdempotencyKey  sql.NullString
}

type MessageRecipient struct {
	MessageID    int64
	AgentID      int64
	State        string
	SnoozedUntil sql.NullInt64
	ReadAt       sql.NullInt64
	AckedAt      sql.NullInt64
}

type MessagesFt struct {
	Subject string
	BodyMd  string
}

type PendingOperation struct {
	ID             int64
	IdempotencyKey string
	OperationType  string
	PayloadJson    string
	AgentName      string
	SessionID      sql.NullString
	CreatedAt      int64
	ExpiresAt      int64
	Attempts       int64
	LastError      sql.NullString
	Status         string
}

type PlanReview struct {
	ID              int64
	PlanReviewID    string
	MessageID       sql.NullInt64
	ThreadID        string
	RequesterID     int64
	ReviewerName    string
	PlanPath        string
	PlanTitle       string
	PlanSummary     sql.NullString
	State           string
	ReviewerComment sql.NullString
	ReviewedBy      sql.NullInt64
	SessionID       sql.NullString
	CreatedAt       int64
	UpdatedAt       int64
	ReviewedAt      sql.NullInt64
}

type Review struct {
	ID          int64
	ReviewID    string
	ThreadID    string
	RequesterID int64
	PrNumber    sql.NullInt64
	Branch      string
	BaseBranch  string
	CommitSha   string
	RepoPath    string
	RemoteUrl   sql.NullString
	ReviewType  string
	Priority    string
	State       string
	CreatedAt   int64
	UpdatedAt   int64
	CompletedAt sql.NullInt64
}

type ReviewIssue struct {
	ID                  int64
	ReviewID            string
	IterationNum        int64
	IssueType           string
	Severity            string
	FilePath            string
	LineStart           int64
	LineEnd             sql.NullInt64
	Title               string
	Description         string
	CodeSnippet         sql.NullString
	Suggestion          sql.NullString
	ClaudeMdRef         sql.NullString
	Status              string
	ResolvedAt          sql.NullInt64
	ResolvedInIteration sql.NullInt64
	CreatedAt           int64
}

type ReviewIteration struct {
	ID                int64
	ReviewID          string
	IterationNum      int64
	ReviewerID        string
	ReviewerSessionID sql.NullString
	Decision          string
	Summary           string
	IssuesJson        sql.NullString
	SuggestionsJson   sql.NullString
	FilesReviewed     int64
	LinesAnalyzed     int64
	DurationMs        int64
	CostUsd           float64
	StartedAt         int64
	CompletedAt       sql.NullInt64
}

type SessionIdentity struct {
	SessionID    string
	AgentID      int64
	ProjectKey   sql.NullString
	GitBranch    sql.NullString
	CreatedAt    int64
	LastActiveAt int64
}

type Subscription struct {
	ID           int64
	AgentID      int64
	TopicID      int64
	SubscribedAt int64
}

type TaskList struct {
	ID           int64
	ListID       string
	AgentID      int64
	WatchPath    string
	CreatedAt    int64
	LastSyncedAt sql.NullInt64
}

type Topic struct {
	ID               int64
	Name             string
	TopicType        string
	RetentionSeconds sql.NullInt64
	CreatedAt        int64
}
