// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plan_reviews.sql

package sqlc

import (
	"context"
	"database/sql"
)

const CreatePlanReview = `-- name: CreatePlanReview :one
INSERT INTO plan_reviews (
    plan_review_id, message_id, thread_id,
    requester_id, reviewer_name,
    plan_path, plan_title, plan_summary,
    state, session_id,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, plan_review_id, message_id, thread_id, requester_id, reviewer_name, plan_path, plan_title, plan_summary, state, reviewer_comment, reviewed_by, session_id, created_at, updated_at, reviewed_at
`

type CreatePlanReviewParams struct {
	PlanReviewID string
	MessageID    sql.NullInt64
	ThreadID     string
	RequesterID  int64
	ReviewerName string
	PlanPath     string
	PlanTitle    string
	PlanSummary  sql.NullString
	State        string
	SessionID    sql.NullString
	CreatedAt    int64
	UpdatedAt    int64
}

func (q *Queries) CreatePlanReview(ctx context.Context, arg CreatePlanReviewParams) (PlanReview, error) {
	row := q.db.QueryRowContext(ctx, CreatePlanReview,
		arg.PlanReviewID,
		arg.MessageID,
		arg.ThreadID,
		arg.RequesterID,
		arg.ReviewerName,
		arg.PlanPath,
		arg.PlanTitle,
		arg.PlanSummary,
		arg.State,
		arg.SessionID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i PlanReview
	err := row.Scan(
		&i.ID,
		&i.PlanReviewID,
		&i.MessageID,
		&i.ThreadID,
		&i.RequesterID,
		&i.ReviewerName,
		&i.PlanPath,
		&i.PlanTitle,
		&i.PlanSummary,
		&i.State,
		&i.ReviewerComment,
		&i.ReviewedBy,
		&i.SessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReviewedAt,
	)
	return i, err
}

const DeletePlanReview = `-- name: DeletePlanReview :exec
DELETE FROM plan_reviews WHERE plan_review_id = ?
`

func (q *Queries) DeletePlanReview(ctx context.Context, planReviewID string) error {
	_, err := q.db.ExecContext(ctx, DeletePlanReview, planReviewID)
	return err
}

const GetPlanReview = `-- name: GetPlanReview :one
SELECT id, plan_review_id, message_id, thread_id, requester_id, reviewer_name, plan_path, plan_title, plan_summary, state, reviewer_comment, reviewed_by, session_id, created_at, updated_at, reviewed_at FROM plan_reviews WHERE plan_review_id = ?
`

func (q *Queries) GetPlanReview(ctx context.Context, planReviewID string) (PlanReview, error) {
	row := q.db.QueryRowContext(ctx, GetPlanReview, planReviewID)
	var i PlanReview
	err := row.Scan(
		&i.ID,
		&i.PlanReviewID,
		&i.MessageID,
		&i.ThreadID,
		&i.RequesterID,
		&i.ReviewerName,
		&i.PlanPath,
		&i.PlanTitle,
		&i.PlanSummary,
		&i.State,
		&i.ReviewerComment,
		&i.ReviewedBy,
		&i.SessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReviewedAt,
	)
	return i, err
}

const GetPlanReviewByID = `-- name: GetPlanReviewByID :one
SELECT id, plan_review_id, message_id, thread_id, requester_id, reviewer_name, plan_path, plan_title, plan_summary, state, reviewer_comment, reviewed_by, session_id, created_at, updated_at, reviewed_at FROM plan_reviews WHERE id = ?
`

func (q *Queries) GetPlanReviewByID(ctx context.Context, id int64) (PlanReview, error) {
	row := q.db.QueryRowContext(ctx, GetPlanReviewByID, id)
	var i PlanReview
	err := row.Scan(
		&i.ID,
		&i.PlanReviewID,
		&i.MessageID,
		&i.ThreadID,
		&i.RequesterID,
		&i.ReviewerName,
		&i.PlanPath,
		&i.PlanTitle,
		&i.PlanSummary,
		&i.State,
		&i.ReviewerComment,
		&i.ReviewedBy,
		&i.SessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReviewedAt,
	)
	return i, err
}

const GetPlanReviewByMessage = `-- name: GetPlanReviewByMessage :one
SELECT id, plan_review_id, message_id, thread_id, requester_id, reviewer_name, plan_path, plan_title, plan_summary, state, reviewer_comment, reviewed_by, session_id, created_at, updated_at, reviewed_at FROM plan_reviews WHERE message_id = ?
`

func (q *Queries) GetPlanReviewByMessage(ctx context.Context, messageID sql.NullInt64) (PlanReview, error) {
	row := q.db.QueryRowContext(ctx, GetPlanReviewByMessage, messageID)
	var i PlanReview
	err := row.Scan(
		&i.ID,
		&i.PlanReviewID,
		&i.MessageID,
		&i.ThreadID,
		&i.RequesterID,
		&i.ReviewerName,
		&i.PlanPath,
		&i.PlanTitle,
		&i.PlanSummary,
		&i.State,
		&i.ReviewerComment,
		&i.ReviewedBy,
		&i.SessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReviewedAt,
	)
	return i, err
}

const GetPlanReviewBySession = `-- name: GetPlanReviewBySession :one
SELECT id, plan_review_id, message_id, thread_id, requester_id, reviewer_name, plan_path, plan_title, plan_summary, state, reviewer_comment, reviewed_by, session_id, created_at, updated_at, reviewed_at FROM plan_reviews
WHERE session_id = ? AND state = 'pending'
ORDER BY created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetPlanReviewBySession(ctx context.Context, sessionID sql.NullString) (PlanReview, error) {
	row := q.db.QueryRowContext(ctx, GetPlanReviewBySession, sessionID)
	var i PlanReview
	err := row.Scan(
		&i.ID,
		&i.PlanReviewID,
		&i.MessageID,
		&i.ThreadID,
		&i.RequesterID,
		&i.ReviewerName,
		&i.PlanPath,
		&i.PlanTitle,
		&i.PlanSummary,
		&i.State,
		&i.ReviewerComment,
		&i.ReviewedBy,
		&i.SessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReviewedAt,
	)
	return i, err
}

const GetPlanReviewByThread = `-- name: GetPlanReviewByThread :one
SELECT id, plan_review_id, message_id, thread_id, requester_id, reviewer_name, plan_path, plan_title, plan_summary, state, reviewer_comment, reviewed_by, session_id, created_at, updated_at, reviewed_at FROM plan_reviews
WHERE thread_id = ?
ORDER BY created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetPlanReviewByThread(ctx context.Context, threadID string) (PlanReview, error) {
	row := q.db.QueryRowContext(ctx, GetPlanReviewByThread, threadID)
	var i PlanReview
	err := row.Scan(
		&i.ID,
		&i.PlanReviewID,
		&i.MessageID,
		&i.ThreadID,
		&i.RequesterID,
		&i.ReviewerName,
		&i.PlanPath,
		&i.PlanTitle,
		&i.PlanSummary,
		&i.State,
		&i.ReviewerComment,
		&i.ReviewedBy,
		&i.SessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReviewedAt,
	)
	return i, err
}

const ListPlanReviews = `-- name: ListPlanReviews :many
SELECT id, plan_review_id, message_id, thread_id, requester_id, reviewer_name, plan_path, plan_title, plan_summary, state, reviewer_comment, reviewed_by, session_id, created_at, updated_at, reviewed_at FROM plan_reviews
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListPlanReviewsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListPlanReviews(ctx context.Context, arg ListPlanReviewsParams) ([]PlanReview, error) {
	rows, err := q.db.QueryContext(ctx, ListPlanReviews, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlanReview
	for rows.Next() {
		var i PlanReview
		if err := rows.Scan(
			&i.ID,
			&i.PlanReviewID,
			&i.MessageID,
			&i.ThreadID,
			&i.RequesterID,
			&i.ReviewerName,
			&i.PlanPath,
			&i.PlanTitle,
			&i.PlanSummary,
			&i.State,
			&i.ReviewerComment,
			&i.ReviewedBy,
			&i.SessionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListPlanReviewsByRequester = `-- name: ListPlanReviewsByRequester :many
SELECT id, plan_review_id, message_id, thread_id, requester_id, reviewer_name, plan_path, plan_title, plan_summary, state, reviewer_comment, reviewed_by, session_id, created_at, updated_at, reviewed_at FROM plan_reviews
WHERE requester_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListPlanReviewsByRequesterParams struct {
	RequesterID int64
	Limit       int64
}

func (q *Queries) ListPlanReviewsByRequester(ctx context.Context, arg ListPlanReviewsByRequesterParams) ([]PlanReview, error) {
	rows, err := q.db.QueryContext(ctx, ListPlanReviewsByRequester, arg.RequesterID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlanReview
	for rows.Next() {
		var i PlanReview
		if err := rows.Scan(
			&i.ID,
			&i.PlanReviewID,
			&i.MessageID,
			&i.ThreadID,
			&i.RequesterID,
			&i.ReviewerName,
			&i.PlanPath,
			&i.PlanTitle,
			&i.PlanSummary,
			&i.State,
			&i.ReviewerComment,
			&i.ReviewedBy,
			&i.SessionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListPlanReviewsByState = `-- name: ListPlanReviewsByState :many
SELECT id, plan_review_id, message_id, thread_id, requester_id, reviewer_name, plan_path, plan_title, plan_summary, state, reviewer_comment, reviewed_by, session_id, created_at, updated_at, reviewed_at FROM plan_reviews
WHERE state = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListPlanReviewsByStateParams struct {
	State string
	Limit int64
}

func (q *Queries) ListPlanReviewsByState(ctx context.Context, arg ListPlanReviewsByStateParams) ([]PlanReview, error) {
	rows, err := q.db.QueryContext(ctx, ListPlanReviewsByState, arg.State, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlanReview
	for rows.Next() {
		var i PlanReview
		if err := rows.Scan(
			&i.ID,
			&i.PlanReviewID,
			&i.MessageID,
			&i.ThreadID,
			&i.RequesterID,
			&i.ReviewerName,
			&i.PlanPath,
			&i.PlanTitle,
			&i.PlanSummary,
			&i.State,
			&i.ReviewerComment,
			&i.ReviewedBy,
			&i.SessionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdatePlanReviewState = `-- name: UpdatePlanReviewState :exec
UPDATE plan_reviews
SET state = ?,
    reviewer_comment = ?,
    reviewed_by = ?,
    updated_at = ?,
    reviewed_at = ?
WHERE plan_review_id = ?
`

type UpdatePlanReviewStateParams struct {
	State           string
	ReviewerComment sql.NullString
	ReviewedBy      sql.NullInt64
	UpdatedAt       int64
	ReviewedAt      sql.NullInt64
	PlanReviewID    string
}

func (q *Queries) UpdatePlanReviewState(ctx context.Context, arg UpdatePlanReviewStateParams) error {
	_, err := q.db.ExecContext(ctx, UpdatePlanReviewState,
		arg.State,
		arg.ReviewerComment,
		arg.ReviewedBy,
		arg.UpdatedAt,
		arg.ReviewedAt,
		arg.PlanReviewID,
	)
	return err
}
