// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountActivitiesByAgentToday(ctx context.Context, arg CountActivitiesByAgentTodayParams) (int64, error)
	CountArchivedByAgent(ctx context.Context, agentID int64) (int64, error)
	CountSentByAgent(ctx context.Context, senderID int64) (int64, error)
	CountSnoozedByAgent(ctx context.Context, agentID int64) (int64, error)
	CountStarredByAgent(ctx context.Context, agentID int64) (int64, error)
	CountSubscribersByTopic(ctx context.Context, topicID int64) (int64, error)
	CountUnreadByAgent(ctx context.Context, agentID int64) (int64, error)
	CountUnreadUrgentByAgent(ctx context.Context, agentID int64) (int64, error)
	CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error)
	CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateMessageRecipient(ctx context.Context, arg CreateMessageRecipientParams) error
	CreateSessionIdentity(ctx context.Context, arg CreateSessionIdentityParams) error
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) error
	CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error)
	DeleteAgent(ctx context.Context, id int64) error
	DeleteMessage(ctx context.Context, id int64) error
	DeleteMessagesByTopicOlderThan(ctx context.Context, arg DeleteMessagesByTopicOlderThanParams) (int64, error)
	DeleteOldActivities(ctx context.Context, createdAt int64) error
	DeleteSessionIdentity(ctx context.Context, sessionID string) error
	DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) error
	DeleteTopic(ctx context.Context, id int64) error
	GetActivity(ctx context.Context, id int64) (Activity, error)
	GetAgent(ctx context.Context, id int64) (Agent, error)
	GetAgentByName(ctx context.Context, name string) (Agent, error)
	GetAgentBySessionID(ctx context.Context, sessionID string) (Agent, error)
	// Global inbox view: all messages across all agents, not archived or trashed.
	GetAllInboxMessages(ctx context.Context, limit int64) ([]GetAllInboxMessagesRow, error)
	// Global sent view: all sent messages across all agents.
	GetAllSentMessages(ctx context.Context, limit int64) ([]GetAllSentMessagesRow, error)
	GetArchivedMessages(ctx context.Context, arg GetArchivedMessagesParams) ([]GetArchivedMessagesRow, error)
	GetConsumerOffset(ctx context.Context, arg GetConsumerOffsetParams) (int64, error)
	GetInboxMessages(ctx context.Context, arg GetInboxMessagesParams) ([]GetInboxMessagesRow, error)
	GetMaxLogOffset(ctx context.Context, topicID int64) (interface{}, error)
	GetMessage(ctx context.Context, id int64) (Message, error)
	GetMessageRecipient(ctx context.Context, arg GetMessageRecipientParams) (MessageRecipient, error)
	GetMessageRecipients(ctx context.Context, messageID int64) ([]MessageRecipient, error)
	GetMessagesByThread(ctx context.Context, threadID string) ([]Message, error)
	GetMessagesByTopic(ctx context.Context, topicID int64) ([]Message, error)
	GetMessagesSinceOffset(ctx context.Context, arg GetMessagesSinceOffsetParams) ([]Message, error)
	GetOrCreateAgentInboxTopic(ctx context.Context, arg GetOrCreateAgentInboxTopicParams) (Topic, error)
	GetOrCreateTopic(ctx context.Context, arg GetOrCreateTopicParams) (Topic, error)
	GetSentMessages(ctx context.Context, arg GetSentMessagesParams) ([]Message, error)
	GetSessionIdentity(ctx context.Context, sessionID string) (SessionIdentity, error)
	GetSessionIdentityByProject(ctx context.Context, projectKey sql.NullString) (SessionIdentity, error)
	GetSnoozedMessages(ctx context.Context, arg GetSnoozedMessagesParams) ([]GetSnoozedMessagesRow, error)
	GetSnoozedMessagesReadyToWake(ctx context.Context, snoozedUntil sql.NullInt64) ([]GetSnoozedMessagesReadyToWakeRow, error)
	GetStarredMessages(ctx context.Context, arg GetStarredMessagesParams) ([]GetStarredMessagesRow, error)
	GetSubscription(ctx context.Context, arg GetSubscriptionParams) (Subscription, error)
	GetTopic(ctx context.Context, id int64) (Topic, error)
	GetTopicByName(ctx context.Context, name string) (Topic, error)
	GetTrashMessages(ctx context.Context, arg GetTrashMessagesParams) ([]GetTrashMessagesRow, error)
	GetUnreadMessages(ctx context.Context, arg GetUnreadMessagesParams) ([]GetUnreadMessagesRow, error)
	ListActivitiesByAgent(ctx context.Context, arg ListActivitiesByAgentParams) ([]Activity, error)
	ListActivitiesByType(ctx context.Context, arg ListActivitiesByTypeParams) ([]Activity, error)
	ListActivitiesSince(ctx context.Context, arg ListActivitiesSinceParams) ([]Activity, error)
	ListAgents(ctx context.Context) ([]Agent, error)
	ListAgentsByProject(ctx context.Context, projectKey sql.NullString) ([]Agent, error)
	ListConsumerOffsetsByAgent(ctx context.Context, agentID int64) ([]ListConsumerOffsetsByAgentRow, error)
	ListMessagesByPriority(ctx context.Context, arg ListMessagesByPriorityParams) ([]Message, error)
	ListRecentActivities(ctx context.Context, limit int64) ([]Activity, error)
	ListSessionIdentitiesByAgent(ctx context.Context, agentID int64) ([]SessionIdentity, error)
	ListSubscriptionsByAgent(ctx context.Context, agentID int64) ([]Topic, error)
	ListSubscriptionsByTopic(ctx context.Context, topicID int64) ([]Agent, error)
	ListTopics(ctx context.Context) ([]Topic, error)
	ListTopicsByType(ctx context.Context, topicType string) ([]Topic, error)
	MarkMessageDeletedBySender(ctx context.Context, arg MarkMessageDeletedBySenderParams) error
	UpdateAgentLastActive(ctx context.Context, arg UpdateAgentLastActiveParams) error
	UpdateAgentSession(ctx context.Context, arg UpdateAgentSessionParams) error
	UpdateRecipientAcked(ctx context.Context, arg UpdateRecipientAckedParams) error
	UpdateRecipientSnoozed(ctx context.Context, arg UpdateRecipientSnoozedParams) error
	UpdateRecipientState(ctx context.Context, arg UpdateRecipientStateParams) (int64, error)
	UpdateSessionIdentityLastActive(ctx context.Context, arg UpdateSessionIdentityLastActiveParams) error
	UpdateTopicRetention(ctx context.Context, arg UpdateTopicRetentionParams) error
	UpsertConsumerOffset(ctx context.Context, arg UpsertConsumerOffsetParams) error
	WakeSnoozedMessages(ctx context.Context, snoozedUntil sql.NullInt64) (int64, error)
}

var _ Querier = (*Queries)(nil)
