// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reading_diffs.sql

package sqlc

import (
	"context"
)

const CountReadingDiffs = `-- name: CountReadingDiffs :one
SELECT COUNT(*) FROM reading_diffs
`

func (q *Queries) CountReadingDiffs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountReadingDiffs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateReadingDiff = `-- name: CreateReadingDiff :one
INSERT INTO reading_diffs (
    cache_key, reading_diff, summary, segments, stats,
    raw_changed, visible_changed, raw_files, visible_files,
    model, rubric_hash, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(cache_key) DO UPDATE SET
    reading_diff = excluded.reading_diff,
    summary = excluded.summary,
    segments = excluded.segments,
    stats = excluded.stats,
    raw_changed = excluded.raw_changed,
    visible_changed = excluded.visible_changed,
    raw_files = excluded.raw_files,
    visible_files = excluded.visible_files,
    model = excluded.model,
    rubric_hash = excluded.rubric_hash,
    created_at = excluded.created_at
RETURNING id, cache_key, reading_diff, summary, segments, stats, raw_changed, visible_changed, raw_files, visible_files, model, rubric_hash, created_at
`

type CreateReadingDiffParams struct {
	CacheKey       string
	ReadingDiff    string
	Summary        string
	Segments       string
	Stats          string
	RawChanged     int64
	VisibleChanged int64
	RawFiles       int64
	VisibleFiles   int64
	Model          string
	RubricHash     string
	CreatedAt      int64
}

func (q *Queries) CreateReadingDiff(ctx context.Context, arg CreateReadingDiffParams) (ReadingDiff, error) {
	row := q.db.QueryRowContext(ctx, CreateReadingDiff,
		arg.CacheKey,
		arg.ReadingDiff,
		arg.Summary,
		arg.Segments,
		arg.Stats,
		arg.RawChanged,
		arg.VisibleChanged,
		arg.RawFiles,
		arg.VisibleFiles,
		arg.Model,
		arg.RubricHash,
		arg.CreatedAt,
	)
	var i ReadingDiff
	err := row.Scan(
		&i.ID,
		&i.CacheKey,
		&i.ReadingDiff,
		&i.Summary,
		&i.Segments,
		&i.Stats,
		&i.RawChanged,
		&i.VisibleChanged,
		&i.RawFiles,
		&i.VisibleFiles,
		&i.Model,
		&i.RubricHash,
		&i.CreatedAt,
	)
	return i, err
}

const DeleteReadingDiffsBefore = `-- name: DeleteReadingDiffsBefore :exec
DELETE FROM reading_diffs
WHERE created_at < ?
`

func (q *Queries) DeleteReadingDiffsBefore(ctx context.Context, createdAt int64) error {
	_, err := q.db.ExecContext(ctx, DeleteReadingDiffsBefore, createdAt)
	return err
}

const GetReadingDiffByKey = `-- name: GetReadingDiffByKey :one
SELECT id, cache_key, reading_diff, summary, segments, stats, raw_changed, visible_changed, raw_files, visible_files, model, rubric_hash, created_at FROM reading_diffs
WHERE cache_key = ?
`

func (q *Queries) GetReadingDiffByKey(ctx context.Context, cacheKey string) (ReadingDiff, error) {
	row := q.db.QueryRowContext(ctx, GetReadingDiffByKey, cacheKey)
	var i ReadingDiff
	err := row.Scan(
		&i.ID,
		&i.CacheKey,
		&i.ReadingDiff,
		&i.Summary,
		&i.Segments,
		&i.Stats,
		&i.RawChanged,
		&i.VisibleChanged,
		&i.RawFiles,
		&i.VisibleFiles,
		&i.Model,
		&i.RubricHash,
		&i.CreatedAt,
	)
	return i, err
}
