// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: summaries.sql

package sqlc

import (
	"context"
)

const CreateAgentSummary = `-- name: CreateAgentSummary :one
INSERT INTO agent_summaries (agent_id, summary, delta, transcript_hash, cost_usd, created_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, agent_id, summary, delta, transcript_hash, cost_usd, created_at
`

type CreateAgentSummaryParams struct {
	AgentID        int64
	Summary        string
	Delta          string
	TranscriptHash string
	CostUsd        float64
	CreatedAt      int64
}

func (q *Queries) CreateAgentSummary(ctx context.Context, arg CreateAgentSummaryParams) (AgentSummary, error) {
	row := q.db.QueryRowContext(ctx, CreateAgentSummary,
		arg.AgentID, arg.Summary, arg.Delta,
		arg.TranscriptHash, arg.CostUsd, arg.CreatedAt,
	)
	var i AgentSummary
	err := row.Scan(
		&i.ID, &i.AgentID, &i.Summary, &i.Delta,
		&i.TranscriptHash, &i.CostUsd, &i.CreatedAt,
	)
	return i, err
}

const GetLatestAgentSummary = `-- name: GetLatestAgentSummary :one
SELECT id, agent_id, summary, delta, transcript_hash, cost_usd, created_at FROM agent_summaries
WHERE agent_id = ?
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestAgentSummary(ctx context.Context, agentID int64) (AgentSummary, error) {
	row := q.db.QueryRowContext(ctx, GetLatestAgentSummary, agentID)
	var i AgentSummary
	err := row.Scan(
		&i.ID, &i.AgentID, &i.Summary, &i.Delta,
		&i.TranscriptHash, &i.CostUsd, &i.CreatedAt,
	)
	return i, err
}

const GetAgentSummaryHistory = `-- name: GetAgentSummaryHistory :many
SELECT id, agent_id, summary, delta, transcript_hash, cost_usd, created_at FROM agent_summaries
WHERE agent_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type GetAgentSummaryHistoryParams struct {
	AgentID int64
	Limit   int64
}

func (q *Queries) GetAgentSummaryHistory(ctx context.Context, arg GetAgentSummaryHistoryParams) ([]AgentSummary, error) {
	rows, err := q.db.QueryContext(
		ctx, GetAgentSummaryHistory, arg.AgentID, arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentSummary
	for rows.Next() {
		var i AgentSummary
		if err := rows.Scan(
			&i.ID, &i.AgentID, &i.Summary, &i.Delta,
			&i.TranscriptHash, &i.CostUsd, &i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const DeleteOldAgentSummaries = `-- name: DeleteOldAgentSummaries :exec
DELETE FROM agent_summaries WHERE created_at < ?
`

func (q *Queries) DeleteOldAgentSummaries(ctx context.Context, createdAt int64) error {
	_, err := q.db.ExecContext(ctx, DeleteOldAgentSummaries, createdAt)
	return err
}
