// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package sqlc

import (
	"context"
	"database/sql"
)

const CountTasksByList = `-- name: CountTasksByList :one

SELECT COUNT(*) FROM agent_tasks WHERE list_id = ?
`

// Task count query for list
func (q *Queries) CountTasksByList(ctx context.Context, listID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountTasksByList, listID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateTask = `-- name: CreateTask :one

INSERT INTO agent_tasks (
    agent_id, list_id, claude_task_id, subject, description,
    active_form, metadata, status, owner, blocked_by, blocks,
    created_at, updated_at, file_path, file_mtime
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, agent_id, list_id, claude_task_id, subject, description, active_form, metadata, status, owner, blocked_by, blocks, created_at, updated_at, started_at, completed_at, file_path, file_mtime
`

type CreateTaskParams struct {
	AgentID      int64
	ListID       string
	ClaudeTaskID string
	Subject      string
	Description  sql.NullString
	ActiveForm   sql.NullString
	Metadata     sql.NullString
	Status       string
	Owner        sql.NullString
	BlockedBy    sql.NullString
	Blocks       sql.NullString
	CreatedAt    int64
	UpdatedAt    int64
	FilePath     sql.NullString
	FileMtime    sql.NullInt64
}

// Task CRUD queries
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (AgentTask, error) {
	row := q.db.QueryRowContext(ctx, CreateTask,
		arg.AgentID,
		arg.ListID,
		arg.ClaudeTaskID,
		arg.Subject,
		arg.Description,
		arg.ActiveForm,
		arg.Metadata,
		arg.Status,
		arg.Owner,
		arg.BlockedBy,
		arg.Blocks,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.FilePath,
		arg.FileMtime,
	)
	var i AgentTask
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.ListID,
		&i.ClaudeTaskID,
		&i.Subject,
		&i.Description,
		&i.ActiveForm,
		&i.Metadata,
		&i.Status,
		&i.Owner,
		&i.BlockedBy,
		&i.Blocks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FilePath,
		&i.FileMtime,
	)
	return i, err
}

const CreateTaskList = `-- name: CreateTaskList :one

INSERT INTO task_lists (list_id, agent_id, watch_path, created_at)
VALUES (?, ?, ?, ?)
RETURNING id, list_id, agent_id, watch_path, created_at, last_synced_at
`

type CreateTaskListParams struct {
	ListID    string
	AgentID   int64
	WatchPath string
	CreatedAt int64
}

// Task list registration queries
func (q *Queries) CreateTaskList(ctx context.Context, arg CreateTaskListParams) (TaskList, error) {
	row := q.db.QueryRowContext(ctx, CreateTaskList,
		arg.ListID,
		arg.AgentID,
		arg.WatchPath,
		arg.CreatedAt,
	)
	var i TaskList
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.AgentID,
		&i.WatchPath,
		&i.CreatedAt,
		&i.LastSyncedAt,
	)
	return i, err
}

const DeleteTask = `-- name: DeleteTask :exec

DELETE FROM agent_tasks WHERE id = ?
`

// Cleanup queries
func (q *Queries) DeleteTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, DeleteTask, id)
	return err
}

const DeleteTaskList = `-- name: DeleteTaskList :exec
DELETE FROM task_lists WHERE list_id = ?
`

func (q *Queries) DeleteTaskList(ctx context.Context, listID string) error {
	_, err := q.db.ExecContext(ctx, DeleteTaskList, listID)
	return err
}

const DeleteTasksByList = `-- name: DeleteTasksByList :exec
DELETE FROM agent_tasks WHERE list_id = ?
`

func (q *Queries) DeleteTasksByList(ctx context.Context, listID string) error {
	_, err := q.db.ExecContext(ctx, DeleteTasksByList, listID)
	return err
}

const GetAllAgentTaskStats = `-- name: GetAllAgentTaskStats :many
SELECT
    agent_id,
    COUNT(*) FILTER (WHERE status = 'pending') as pending_count,
    COUNT(*) FILTER (WHERE status = 'in_progress') as in_progress_count,
    COUNT(*) FILTER (WHERE status = 'pending' AND blocked_by != '[]') as blocked_count,
    COUNT(*) FILTER (WHERE status = 'completed' AND completed_at > ?) as completed_today
FROM agent_tasks
GROUP BY agent_id
`

type GetAllAgentTaskStatsRow struct {
	AgentID         int64
	PendingCount    int64
	InProgressCount int64
	BlockedCount    int64
	CompletedToday  int64
}

func (q *Queries) GetAllAgentTaskStats(ctx context.Context) ([]GetAllAgentTaskStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, GetAllAgentTaskStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllAgentTaskStatsRow
	for rows.Next() {
		var i GetAllAgentTaskStatsRow
		if err := rows.Scan(
			&i.AgentID,
			&i.PendingCount,
			&i.InProgressCount,
			&i.BlockedCount,
			&i.CompletedToday,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetAllTaskStats = `-- name: GetAllTaskStats :one
SELECT
    COUNT(*) FILTER (WHERE status = 'pending') as pending_count,
    COUNT(*) FILTER (WHERE status = 'in_progress') as in_progress_count,
    COUNT(*) FILTER (WHERE status = 'completed') as completed_count,
    COUNT(*) FILTER (WHERE status = 'pending' AND blocked_by != '[]') as blocked_count,
    COUNT(*) FILTER (WHERE status = 'completed' AND completed_at > ?) as completed_today
FROM agent_tasks
`

type GetAllTaskStatsRow struct {
	PendingCount    int64
	InProgressCount int64
	CompletedCount  int64
	BlockedCount    int64
	CompletedToday  int64
}

func (q *Queries) GetAllTaskStats(ctx context.Context) (GetAllTaskStatsRow, error) {
	row := q.db.QueryRowContext(ctx, GetAllTaskStats)
	var i GetAllTaskStatsRow
	err := row.Scan(
		&i.PendingCount,
		&i.InProgressCount,
		&i.CompletedCount,
		&i.BlockedCount,
		&i.CompletedToday,
	)
	return i, err
}

const GetTask = `-- name: GetTask :one
SELECT id, agent_id, list_id, claude_task_id, subject, description, active_form, metadata, status, owner, blocked_by, blocks, created_at, updated_at, started_at, completed_at, file_path, file_mtime FROM agent_tasks WHERE id = ?
`

func (q *Queries) GetTask(ctx context.Context, id int64) (AgentTask, error) {
	row := q.db.QueryRowContext(ctx, GetTask, id)
	var i AgentTask
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.ListID,
		&i.ClaudeTaskID,
		&i.Subject,
		&i.Description,
		&i.ActiveForm,
		&i.Metadata,
		&i.Status,
		&i.Owner,
		&i.BlockedBy,
		&i.Blocks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FilePath,
		&i.FileMtime,
	)
	return i, err
}

const GetTaskByClaudeID = `-- name: GetTaskByClaudeID :one
SELECT id, agent_id, list_id, claude_task_id, subject, description, active_form, metadata, status, owner, blocked_by, blocks, created_at, updated_at, started_at, completed_at, file_path, file_mtime FROM agent_tasks
WHERE list_id = ? AND claude_task_id = ?
`

type GetTaskByClaudeIDParams struct {
	ListID       string
	ClaudeTaskID string
}

func (q *Queries) GetTaskByClaudeID(ctx context.Context, arg GetTaskByClaudeIDParams) (AgentTask, error) {
	row := q.db.QueryRowContext(ctx, GetTaskByClaudeID, arg.ListID, arg.ClaudeTaskID)
	var i AgentTask
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.ListID,
		&i.ClaudeTaskID,
		&i.Subject,
		&i.Description,
		&i.ActiveForm,
		&i.Metadata,
		&i.Status,
		&i.Owner,
		&i.BlockedBy,
		&i.Blocks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FilePath,
		&i.FileMtime,
	)
	return i, err
}

const GetTaskList = `-- name: GetTaskList :one
SELECT id, list_id, agent_id, watch_path, created_at, last_synced_at FROM task_lists WHERE list_id = ?
`

func (q *Queries) GetTaskList(ctx context.Context, listID string) (TaskList, error) {
	row := q.db.QueryRowContext(ctx, GetTaskList, listID)
	var i TaskList
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.AgentID,
		&i.WatchPath,
		&i.CreatedAt,
		&i.LastSyncedAt,
	)
	return i, err
}

const GetTaskListByID = `-- name: GetTaskListByID :one
SELECT id, list_id, agent_id, watch_path, created_at, last_synced_at FROM task_lists WHERE id = ?
`

func (q *Queries) GetTaskListByID(ctx context.Context, id int64) (TaskList, error) {
	row := q.db.QueryRowContext(ctx, GetTaskListByID, id)
	var i TaskList
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.AgentID,
		&i.WatchPath,
		&i.CreatedAt,
		&i.LastSyncedAt,
	)
	return i, err
}

const GetTaskStatsByAgent = `-- name: GetTaskStatsByAgent :one

SELECT
    COUNT(*) FILTER (WHERE status = 'pending') as pending_count,
    COUNT(*) FILTER (WHERE status = 'in_progress') as in_progress_count,
    COUNT(*) FILTER (WHERE status = 'completed') as completed_count,
    COUNT(*) FILTER (WHERE status = 'pending' AND blocked_by != '[]') as blocked_count,
    COUNT(*) FILTER (WHERE status = 'pending' AND (owner IS NULL OR owner = '') AND (blocked_by IS NULL OR blocked_by = '[]')) as available_count,
    COUNT(*) FILTER (WHERE status = 'completed' AND completed_at > ?) as completed_today
FROM agent_tasks
WHERE agent_id = ?
`

type GetTaskStatsByAgentRow struct {
	PendingCount    int64
	InProgressCount int64
	CompletedCount  int64
	BlockedCount    int64
	AvailableCount  int64
	CompletedToday  int64
}

// Task statistics queries
func (q *Queries) GetTaskStatsByAgent(ctx context.Context, agentID int64) (GetTaskStatsByAgentRow, error) {
	row := q.db.QueryRowContext(ctx, GetTaskStatsByAgent, agentID)
	var i GetTaskStatsByAgentRow
	err := row.Scan(
		&i.PendingCount,
		&i.InProgressCount,
		&i.CompletedCount,
		&i.BlockedCount,
		&i.AvailableCount,
		&i.CompletedToday,
	)
	return i, err
}

const GetTaskStatsByList = `-- name: GetTaskStatsByList :one
SELECT
    COUNT(*) FILTER (WHERE status = 'pending') as pending_count,
    COUNT(*) FILTER (WHERE status = 'in_progress') as in_progress_count,
    COUNT(*) FILTER (WHERE status = 'completed') as completed_count,
    COUNT(*) FILTER (WHERE status = 'pending' AND blocked_by != '[]') as blocked_count,
    COUNT(*) FILTER (WHERE status = 'pending' AND (owner IS NULL OR owner = '') AND (blocked_by IS NULL OR blocked_by = '[]')) as available_count,
    COUNT(*) FILTER (WHERE status = 'completed' AND completed_at > ?) as completed_today
FROM agent_tasks
WHERE list_id = ?
`

type GetTaskStatsByListRow struct {
	PendingCount    int64
	InProgressCount int64
	CompletedCount  int64
	BlockedCount    int64
	AvailableCount  int64
	CompletedToday  int64
}

func (q *Queries) GetTaskStatsByList(ctx context.Context, listID string) (GetTaskStatsByListRow, error) {
	row := q.db.QueryRowContext(ctx, GetTaskStatsByList, listID)
	var i GetTaskStatsByListRow
	err := row.Scan(
		&i.PendingCount,
		&i.InProgressCount,
		&i.CompletedCount,
		&i.BlockedCount,
		&i.AvailableCount,
		&i.CompletedToday,
	)
	return i, err
}

const ListActiveTasksByAgent = `-- name: ListActiveTasksByAgent :many
SELECT id, agent_id, list_id, claude_task_id, subject, description, active_form, metadata, status, owner, blocked_by, blocks, created_at, updated_at, started_at, completed_at, file_path, file_mtime FROM agent_tasks
WHERE agent_id = ? AND status IN ('pending', 'in_progress')
ORDER BY
    CASE status WHEN 'in_progress' THEN 0 ELSE 1 END,
    created_at ASC
`

func (q *Queries) ListActiveTasksByAgent(ctx context.Context, agentID int64) ([]AgentTask, error) {
	rows, err := q.db.QueryContext(ctx, ListActiveTasksByAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentTask
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.ListID,
			&i.ClaudeTaskID,
			&i.Subject,
			&i.Description,
			&i.ActiveForm,
			&i.Metadata,
			&i.Status,
			&i.Owner,
			&i.BlockedBy,
			&i.Blocks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FilePath,
			&i.FileMtime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAllTasks = `-- name: ListAllTasks :many
SELECT id, agent_id, list_id, claude_task_id, subject, description, active_form, metadata, status, owner, blocked_by, blocks, created_at, updated_at, started_at, completed_at, file_path, file_mtime FROM agent_tasks
ORDER BY
    CASE status
        WHEN 'in_progress' THEN 0
        WHEN 'pending' THEN 1
        ELSE 2
    END,
    updated_at DESC
LIMIT ? OFFSET ?
`

type ListAllTasksParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListAllTasks(ctx context.Context, arg ListAllTasksParams) ([]AgentTask, error) {
	rows, err := q.db.QueryContext(ctx, ListAllTasks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentTask
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.ListID,
			&i.ClaudeTaskID,
			&i.Subject,
			&i.Description,
			&i.ActiveForm,
			&i.Metadata,
			&i.Status,
			&i.Owner,
			&i.BlockedBy,
			&i.Blocks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FilePath,
			&i.FileMtime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAvailableTasks = `-- name: ListAvailableTasks :many
SELECT id, agent_id, list_id, claude_task_id, subject, description, active_form, metadata, status, owner, blocked_by, blocks, created_at, updated_at, started_at, completed_at, file_path, file_mtime FROM agent_tasks
WHERE agent_id = ?
  AND status = 'pending'
  AND (owner IS NULL OR owner = '')
  AND (blocked_by IS NULL OR blocked_by = '[]')
ORDER BY created_at ASC
`

func (q *Queries) ListAvailableTasks(ctx context.Context, agentID int64) ([]AgentTask, error) {
	rows, err := q.db.QueryContext(ctx, ListAvailableTasks, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentTask
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.ListID,
			&i.ClaudeTaskID,
			&i.Subject,
			&i.Description,
			&i.ActiveForm,
			&i.Metadata,
			&i.Status,
			&i.Owner,
			&i.BlockedBy,
			&i.Blocks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FilePath,
			&i.FileMtime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListBlockedTasks = `-- name: ListBlockedTasks :many
SELECT id, agent_id, list_id, claude_task_id, subject, description, active_form, metadata, status, owner, blocked_by, blocks, created_at, updated_at, started_at, completed_at, file_path, file_mtime FROM agent_tasks
WHERE agent_id = ?
  AND status = 'pending'
  AND blocked_by != '[]'
ORDER BY created_at ASC
`

func (q *Queries) ListBlockedTasks(ctx context.Context, agentID int64) ([]AgentTask, error) {
	rows, err := q.db.QueryContext(ctx, ListBlockedTasks, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentTask
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.ListID,
			&i.ClaudeTaskID,
			&i.Subject,
			&i.Description,
			&i.ActiveForm,
			&i.Metadata,
			&i.Status,
			&i.Owner,
			&i.BlockedBy,
			&i.Blocks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FilePath,
			&i.FileMtime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListInProgressTasks = `-- name: ListInProgressTasks :many
SELECT id, agent_id, list_id, claude_task_id, subject, description, active_form, metadata, status, owner, blocked_by, blocks, created_at, updated_at, started_at, completed_at, file_path, file_mtime FROM agent_tasks
WHERE agent_id = ? AND status = 'in_progress'
ORDER BY started_at ASC
`

func (q *Queries) ListInProgressTasks(ctx context.Context, agentID int64) ([]AgentTask, error) {
	rows, err := q.db.QueryContext(ctx, ListInProgressTasks, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentTask
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.ListID,
			&i.ClaudeTaskID,
			&i.Subject,
			&i.Description,
			&i.ActiveForm,
			&i.Metadata,
			&i.Status,
			&i.Owner,
			&i.BlockedBy,
			&i.Blocks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FilePath,
			&i.FileMtime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListPendingTasks = `-- name: ListPendingTasks :many
SELECT id, agent_id, list_id, claude_task_id, subject, description, active_form, metadata, status, owner, blocked_by, blocks, created_at, updated_at, started_at, completed_at, file_path, file_mtime FROM agent_tasks
WHERE agent_id = ? AND status = 'pending'
ORDER BY created_at ASC
`

func (q *Queries) ListPendingTasks(ctx context.Context, agentID int64) ([]AgentTask, error) {
	rows, err := q.db.QueryContext(ctx, ListPendingTasks, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentTask
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.ListID,
			&i.ClaudeTaskID,
			&i.Subject,
			&i.Description,
			&i.ActiveForm,
			&i.Metadata,
			&i.Status,
			&i.Owner,
			&i.BlockedBy,
			&i.Blocks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FilePath,
			&i.FileMtime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListRecentCompletedTasks = `-- name: ListRecentCompletedTasks :many
SELECT id, agent_id, list_id, claude_task_id, subject, description, active_form, metadata, status, owner, blocked_by, blocks, created_at, updated_at, started_at, completed_at, file_path, file_mtime FROM agent_tasks
WHERE agent_id = ?
  AND status = 'completed'
  AND completed_at > ?
ORDER BY completed_at DESC
LIMIT ?
`

type ListRecentCompletedTasksParams struct {
	AgentID     int64
	CompletedAt sql.NullInt64
	Limit       int64
}

func (q *Queries) ListRecentCompletedTasks(ctx context.Context, arg ListRecentCompletedTasksParams) ([]AgentTask, error) {
	rows, err := q.db.QueryContext(ctx, ListRecentCompletedTasks, arg.AgentID, arg.CompletedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentTask
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.ListID,
			&i.ClaudeTaskID,
			&i.Subject,
			&i.Description,
			&i.ActiveForm,
			&i.Metadata,
			&i.Status,
			&i.Owner,
			&i.BlockedBy,
			&i.Blocks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FilePath,
			&i.FileMtime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTaskLists = `-- name: ListTaskLists :many
SELECT id, list_id, agent_id, watch_path, created_at, last_synced_at FROM task_lists
ORDER BY created_at DESC
`

func (q *Queries) ListTaskLists(ctx context.Context) ([]TaskList, error) {
	rows, err := q.db.QueryContext(ctx, ListTaskLists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskList
	for rows.Next() {
		var i TaskList
		if err := rows.Scan(
			&i.ID,
			&i.ListID,
			&i.AgentID,
			&i.WatchPath,
			&i.CreatedAt,
			&i.LastSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTaskListsByAgent = `-- name: ListTaskListsByAgent :many
SELECT id, list_id, agent_id, watch_path, created_at, last_synced_at FROM task_lists
WHERE agent_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListTaskListsByAgent(ctx context.Context, agentID int64) ([]TaskList, error) {
	rows, err := q.db.QueryContext(ctx, ListTaskListsByAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskList
	for rows.Next() {
		var i TaskList
		if err := rows.Scan(
			&i.ID,
			&i.ListID,
			&i.AgentID,
			&i.WatchPath,
			&i.CreatedAt,
			&i.LastSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTasksByAgent = `-- name: ListTasksByAgent :many

SELECT id, agent_id, list_id, claude_task_id, subject, description, active_form, metadata, status, owner, blocked_by, blocks, created_at, updated_at, started_at, completed_at, file_path, file_mtime FROM agent_tasks
WHERE agent_id = ?
ORDER BY
    CASE status
        WHEN 'in_progress' THEN 0
        WHEN 'pending' THEN 1
        ELSE 2
    END,
    updated_at DESC
`

// Task listing queries
func (q *Queries) ListTasksByAgent(ctx context.Context, agentID int64) ([]AgentTask, error) {
	rows, err := q.db.QueryContext(ctx, ListTasksByAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentTask
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.ListID,
			&i.ClaudeTaskID,
			&i.Subject,
			&i.Description,
			&i.ActiveForm,
			&i.Metadata,
			&i.Status,
			&i.Owner,
			&i.BlockedBy,
			&i.Blocks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FilePath,
			&i.FileMtime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTasksByAgentWithLimit = `-- name: ListTasksByAgentWithLimit :many
SELECT id, agent_id, list_id, claude_task_id, subject, description, active_form, metadata, status, owner, blocked_by, blocks, created_at, updated_at, started_at, completed_at, file_path, file_mtime FROM agent_tasks
WHERE agent_id = ?
ORDER BY
    CASE status
        WHEN 'in_progress' THEN 0
        WHEN 'pending' THEN 1
        ELSE 2
    END,
    updated_at DESC
LIMIT ? OFFSET ?
`

type ListTasksByAgentWithLimitParams struct {
	AgentID int64
	Limit   int64
	Offset  int64
}

func (q *Queries) ListTasksByAgentWithLimit(ctx context.Context, arg ListTasksByAgentWithLimitParams) ([]AgentTask, error) {
	rows, err := q.db.QueryContext(ctx, ListTasksByAgentWithLimit, arg.AgentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentTask
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.ListID,
			&i.ClaudeTaskID,
			&i.Subject,
			&i.Description,
			&i.ActiveForm,
			&i.Metadata,
			&i.Status,
			&i.Owner,
			&i.BlockedBy,
			&i.Blocks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FilePath,
			&i.FileMtime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTasksByList = `-- name: ListTasksByList :many
SELECT id, agent_id, list_id, claude_task_id, subject, description, active_form, metadata, status, owner, blocked_by, blocks, created_at, updated_at, started_at, completed_at, file_path, file_mtime FROM agent_tasks
WHERE list_id = ?
ORDER BY
    CASE status
        WHEN 'in_progress' THEN 0
        WHEN 'pending' THEN 1
        ELSE 2
    END,
    updated_at DESC
`

func (q *Queries) ListTasksByList(ctx context.Context, listID string) ([]AgentTask, error) {
	rows, err := q.db.QueryContext(ctx, ListTasksByList, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentTask
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.ListID,
			&i.ClaudeTaskID,
			&i.Subject,
			&i.Description,
			&i.ActiveForm,
			&i.Metadata,
			&i.Status,
			&i.Owner,
			&i.BlockedBy,
			&i.Blocks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FilePath,
			&i.FileMtime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTasksByStatus = `-- name: ListTasksByStatus :many
SELECT id, agent_id, list_id, claude_task_id, subject, description, active_form, metadata, status, owner, blocked_by, blocks, created_at, updated_at, started_at, completed_at, file_path, file_mtime FROM agent_tasks
WHERE status = ?
ORDER BY updated_at DESC
LIMIT ? OFFSET ?
`

type ListTasksByStatusParams struct {
	Status string
	Limit  int64
	Offset int64
}

func (q *Queries) ListTasksByStatus(ctx context.Context, arg ListTasksByStatusParams) ([]AgentTask, error) {
	rows, err := q.db.QueryContext(ctx, ListTasksByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentTask
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.ListID,
			&i.ClaudeTaskID,
			&i.Subject,
			&i.Description,
			&i.ActiveForm,
			&i.Metadata,
			&i.Status,
			&i.Owner,
			&i.BlockedBy,
			&i.Blocks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FilePath,
			&i.FileMtime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const MarkTasksDeletedByList = `-- name: MarkTasksDeletedByList :exec
UPDATE agent_tasks
SET status = 'deleted', updated_at = ?
WHERE list_id = ?
  AND claude_task_id NOT IN (/*SLICE:active_ids*/?)
  AND status NOT IN ('completed', 'deleted')
`

type MarkTasksDeletedByListParams struct {
	UpdatedAt    int64
	ListID       string
	ClaudeTaskID string
}

func (q *Queries) MarkTasksDeletedByList(ctx context.Context, arg MarkTasksDeletedByListParams) error {
	_, err := q.db.ExecContext(ctx, MarkTasksDeletedByList, arg.UpdatedAt, arg.ListID, arg.ClaudeTaskID)
	return err
}

const PruneOldTasks = `-- name: PruneOldTasks :exec
DELETE FROM agent_tasks
WHERE status IN ('completed', 'deleted')
  AND completed_at < ?
`

func (q *Queries) PruneOldTasks(ctx context.Context, completedAt sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, PruneOldTasks, completedAt)
	return err
}

const UpdateTaskListSyncTime = `-- name: UpdateTaskListSyncTime :exec
UPDATE task_lists
SET last_synced_at = ?
WHERE list_id = ?
`

type UpdateTaskListSyncTimeParams struct {
	LastSyncedAt sql.NullInt64
	ListID       string
}

func (q *Queries) UpdateTaskListSyncTime(ctx context.Context, arg UpdateTaskListSyncTimeParams) error {
	_, err := q.db.ExecContext(ctx, UpdateTaskListSyncTime, arg.LastSyncedAt, arg.ListID)
	return err
}

const UpdateTaskOwner = `-- name: UpdateTaskOwner :exec
UPDATE agent_tasks
SET owner = ?, updated_at = ?
WHERE list_id = ? AND claude_task_id = ?
`

type UpdateTaskOwnerParams struct {
	Owner        sql.NullString
	UpdatedAt    int64
	ListID       string
	ClaudeTaskID string
}

func (q *Queries) UpdateTaskOwner(ctx context.Context, arg UpdateTaskOwnerParams) error {
	_, err := q.db.ExecContext(ctx, UpdateTaskOwner,
		arg.Owner,
		arg.UpdatedAt,
		arg.ListID,
		arg.ClaudeTaskID,
	)
	return err
}

const UpdateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE agent_tasks
SET status = ?,
    updated_at = ?,
    started_at = CASE WHEN ? = 'in_progress' AND started_at IS NULL THEN ? ELSE started_at END,
    completed_at = CASE WHEN ? = 'completed' THEN ? ELSE completed_at END
WHERE list_id = ? AND claude_task_id = ?
`

type UpdateTaskStatusParams struct {
	Status       string
	UpdatedAt    int64
	Column3      interface{}
	StartedAt    sql.NullInt64
	Column5      interface{}
	CompletedAt  sql.NullInt64
	ListID       string
	ClaudeTaskID string
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.ExecContext(ctx, UpdateTaskStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.Column3,
		arg.StartedAt,
		arg.Column5,
		arg.CompletedAt,
		arg.ListID,
		arg.ClaudeTaskID,
	)
	return err
}

const UpsertTask = `-- name: UpsertTask :one
INSERT INTO agent_tasks (
    agent_id, list_id, claude_task_id, subject, description,
    active_form, metadata, status, owner, blocked_by, blocks,
    created_at, updated_at, started_at, completed_at, file_path, file_mtime
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(list_id, claude_task_id) DO UPDATE SET
    subject = COALESCE(NULLIF(excluded.subject, ''), agent_tasks.subject),
    description = COALESCE(NULLIF(excluded.description, ''), agent_tasks.description),
    active_form = COALESCE(NULLIF(excluded.active_form, ''), agent_tasks.active_form),
    metadata = COALESCE(NULLIF(excluded.metadata, ''), agent_tasks.metadata),
    status = excluded.status,
    owner = COALESCE(NULLIF(excluded.owner, ''), agent_tasks.owner),
    blocked_by = excluded.blocked_by,
    blocks = excluded.blocks,
    updated_at = excluded.updated_at,
    started_at = CASE
        WHEN excluded.status = 'in_progress' AND agent_tasks.started_at IS NULL
        THEN excluded.updated_at
        ELSE COALESCE(agent_tasks.started_at, excluded.started_at)
    END,
    completed_at = CASE
        WHEN excluded.status = 'completed' AND agent_tasks.completed_at IS NULL
        THEN excluded.updated_at
        ELSE COALESCE(agent_tasks.completed_at, excluded.completed_at)
    END,
    file_path = excluded.file_path,
    file_mtime = excluded.file_mtime
RETURNING id, agent_id, list_id, claude_task_id, subject, description, active_form, metadata, status, owner, blocked_by, blocks, created_at, updated_at, started_at, completed_at, file_path, file_mtime
`

type UpsertTaskParams struct {
	AgentID      int64
	ListID       string
	ClaudeTaskID string
	Subject      string
	Description  sql.NullString
	ActiveForm   sql.NullString
	Metadata     sql.NullString
	Status       string
	Owner        sql.NullString
	BlockedBy    sql.NullString
	Blocks       sql.NullString
	CreatedAt    int64
	UpdatedAt    int64
	StartedAt    sql.NullInt64
	CompletedAt  sql.NullInt64
	FilePath     sql.NullString
	FileMtime    sql.NullInt64
}

func (q *Queries) UpsertTask(ctx context.Context, arg UpsertTaskParams) (AgentTask, error) {
	row := q.db.QueryRowContext(ctx, UpsertTask,
		arg.AgentID,
		arg.ListID,
		arg.ClaudeTaskID,
		arg.Subject,
		arg.Description,
		arg.ActiveForm,
		arg.Metadata,
		arg.Status,
		arg.Owner,
		arg.BlockedBy,
		arg.Blocks,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.StartedAt,
		arg.CompletedAt,
		arg.FilePath,
		arg.FileMtime,
	)
	var i AgentTask
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.ListID,
		&i.ClaudeTaskID,
		&i.Subject,
		&i.Description,
		&i.ActiveForm,
		&i.Metadata,
		&i.Status,
		&i.Owner,
		&i.BlockedBy,
		&i.Blocks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FilePath,
		&i.FileMtime,
	)
	return i, err
}
