-- Code generated by merge-sql-schemas. DO NOT EDIT.
-- This file is the consolidated schema from all migrations.

CREATE TABLE activities (
    id INTEGER PRIMARY KEY,
    agent_id INTEGER NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
    activity_type TEXT NOT NULL CHECK (activity_type IN (
        'commit', 'message', 'session_start', 'session_complete',
        'decision', 'error', 'blocker', 'heartbeat', 'task_complete'
    )),
    description TEXT NOT NULL,
    metadata TEXT, -- JSON blob for additional context.
    created_at INTEGER NOT NULL
);

CREATE TABLE agents (
    id INTEGER PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    project_key TEXT,
    git_branch TEXT,
    current_session_id TEXT,
    created_at INTEGER NOT NULL,
    last_active_at INTEGER NOT NULL
);

CREATE TABLE consumer_offsets (
    agent_id INTEGER NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
    topic_id INTEGER NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
    last_offset INTEGER NOT NULL DEFAULT 0,
    updated_at INTEGER NOT NULL,
    PRIMARY KEY(agent_id, topic_id)
);

CREATE TABLE message_recipients (
    message_id INTEGER NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    agent_id INTEGER NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
    state TEXT NOT NULL DEFAULT 'unread' CHECK (state IN ('unread', 'read', 'starred', 'snoozed', 'archived', 'trash')),
    snoozed_until INTEGER,
    read_at INTEGER,
    acked_at INTEGER,
    PRIMARY KEY(message_id, agent_id)
);

CREATE TABLE messages (
    id INTEGER PRIMARY KEY,
    thread_id TEXT NOT NULL,
    topic_id INTEGER NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
    log_offset INTEGER NOT NULL,
    sender_id INTEGER NOT NULL REFERENCES agents(id),
    subject TEXT NOT NULL,
    body_md TEXT NOT NULL,
    priority TEXT NOT NULL DEFAULT 'normal' CHECK (priority IN ('urgent', 'normal', 'low')),
    deadline_at INTEGER,
    attachments TEXT,
    created_at INTEGER NOT NULL, deleted_by_sender INTEGER NOT NULL DEFAULT 0, metadata TEXT, idempotency_key TEXT,
    UNIQUE(topic_id, log_offset)
);

CREATE TABLE pending_operations (
    id INTEGER PRIMARY KEY,
    idempotency_key TEXT UNIQUE NOT NULL,
    operation_type TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    agent_name TEXT NOT NULL,
    session_id TEXT,
    created_at INTEGER NOT NULL,
    expires_at INTEGER NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    status TEXT NOT NULL DEFAULT 'pending'
);

CREATE TABLE review_issues (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    review_id TEXT NOT NULL REFERENCES reviews(review_id),
    iteration_num INTEGER NOT NULL,

    issue_type TEXT NOT NULL
        CHECK (issue_type IN (
            'bug', 'security', 'claude_md_violation', 'logic_error',
            'performance', 'style', 'documentation', 'other'
        )),
    severity TEXT NOT NULL
        CHECK (severity IN ('critical', 'high', 'medium', 'low')),

    file_path TEXT NOT NULL,
    line_start INTEGER NOT NULL,
    line_end INTEGER,

    title TEXT NOT NULL,
    description TEXT NOT NULL,
    code_snippet TEXT,
    suggestion TEXT,
    claude_md_ref TEXT,

    -- Resolution tracking.
    status TEXT NOT NULL DEFAULT 'open'
        CHECK (status IN ('open', 'fixed', 'wont_fix', 'duplicate')),
    resolved_at INTEGER,
    resolved_in_iteration INTEGER,

    created_at INTEGER NOT NULL
);

CREATE TABLE review_iterations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    review_id TEXT NOT NULL REFERENCES reviews(review_id),
    iteration_num INTEGER NOT NULL,

    -- Reviewer info.
    reviewer_id TEXT NOT NULL,                -- Reviewer persona name.
    reviewer_session_id TEXT,                 -- Claude session ID for this review.

    -- Results.
    decision TEXT NOT NULL
        CHECK (decision IN ('approve', 'request_changes', 'comment')),
    summary TEXT NOT NULL,
    issues_json TEXT,                         -- JSON array of ReviewIssue.
    suggestions_json TEXT,                    -- JSON array of Suggestion.

    -- Metrics.
    files_reviewed INTEGER NOT NULL DEFAULT 0,
    lines_analyzed INTEGER NOT NULL DEFAULT 0,
    duration_ms INTEGER NOT NULL DEFAULT 0,
    cost_usd REAL NOT NULL DEFAULT 0,

    -- Timestamps (Unix epoch seconds).
    started_at INTEGER NOT NULL,
    completed_at INTEGER,

    UNIQUE(review_id, iteration_num, reviewer_id)
);

CREATE TABLE reviews (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    review_id TEXT NOT NULL UNIQUE,           -- UUID.
    thread_id TEXT NOT NULL,                  -- Links to message thread (plain TEXT, no FK).

    requester_id INTEGER NOT NULL REFERENCES agents(id),

    -- PR information.
    pr_number INTEGER,
    branch TEXT NOT NULL,
    base_branch TEXT NOT NULL DEFAULT 'main',
    commit_sha TEXT NOT NULL,
    repo_path TEXT NOT NULL,
    remote_url TEXT,

    -- Configuration.
    review_type TEXT NOT NULL DEFAULT 'full'
        CHECK (review_type IN ('full', 'incremental', 'security', 'performance')),
    priority TEXT NOT NULL DEFAULT 'normal'
        CHECK (priority IN ('urgent', 'normal', 'low')),

    -- FSM state.
    state TEXT NOT NULL DEFAULT 'new'
        CHECK (state IN (
            'new', 'pending_review', 'under_review',
            'changes_requested', 're_review',
            'approved', 'rejected', 'cancelled'
        )),

    -- Timestamps (Unix epoch seconds).
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    completed_at INTEGER
);

CREATE TABLE session_identities (
    session_id TEXT PRIMARY KEY,
    agent_id INTEGER NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
    project_key TEXT,
    git_branch TEXT,
    created_at INTEGER NOT NULL,
    last_active_at INTEGER NOT NULL
);

CREATE TABLE subscriptions (
    id INTEGER PRIMARY KEY,
    agent_id INTEGER NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
    topic_id INTEGER NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
    subscribed_at INTEGER NOT NULL,
    UNIQUE(agent_id, topic_id)
);

CREATE TABLE topics (
    id INTEGER PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    topic_type TEXT NOT NULL CHECK (topic_type IN ('direct', 'broadcast', 'queue')),
    retention_seconds INTEGER DEFAULT 604800,
    created_at INTEGER NOT NULL
);

CREATE VIRTUAL TABLE messages_fts USING fts5(
    subject,
    body_md,
    content=messages,
    content_rowid=id
);

CREATE INDEX idx_activities_agent ON activities(agent_id);

CREATE INDEX idx_activities_created ON activities(created_at DESC);

CREATE INDEX idx_activities_type ON activities(activity_type);

CREATE INDEX idx_agents_name ON agents(name);

CREATE INDEX idx_agents_project ON agents(project_key);

CREATE INDEX idx_messages_created ON messages(created_at);

CREATE INDEX idx_messages_deleted ON messages(deleted_by_sender);

CREATE UNIQUE INDEX idx_messages_idempotency_key
    ON messages(idempotency_key) WHERE idempotency_key IS NOT NULL;

CREATE INDEX idx_messages_priority ON messages(priority);

CREATE INDEX idx_messages_sender ON messages(sender_id);

CREATE INDEX idx_messages_thread ON messages(thread_id);

CREATE INDEX idx_messages_topic ON messages(topic_id);

CREATE INDEX idx_pending_expires
    ON pending_operations(expires_at);

CREATE INDEX idx_pending_status
    ON pending_operations(status);

CREATE INDEX idx_recipients_agent ON message_recipients(agent_id);

CREATE INDEX idx_recipients_snoozed ON message_recipients(snoozed_until) WHERE snoozed_until IS NOT NULL;

CREATE INDEX idx_recipients_state ON message_recipients(state);

CREATE INDEX idx_review_issues_review ON review_issues(review_id);

CREATE INDEX idx_review_issues_severity ON review_issues(severity);

CREATE INDEX idx_review_issues_status ON review_issues(status);

CREATE INDEX idx_review_iterations_review ON review_iterations(review_id);

CREATE INDEX idx_reviews_created ON reviews(created_at DESC);

CREATE INDEX idx_reviews_requester ON reviews(requester_id);

CREATE INDEX idx_reviews_state ON reviews(state);

CREATE INDEX idx_reviews_thread ON reviews(thread_id);

CREATE INDEX idx_session_identities_agent ON session_identities(agent_id);

CREATE INDEX idx_session_identities_project ON session_identities(project_key);

CREATE INDEX idx_subscriptions_agent ON subscriptions(agent_id);

CREATE INDEX idx_subscriptions_topic ON subscriptions(topic_id);

CREATE INDEX idx_topics_name ON topics(name);

CREATE INDEX idx_topics_type ON topics(topic_type);

CREATE TRIGGER check_activity_type_reviews
BEFORE INSERT ON activities
WHEN new.activity_type IN (
    'review_requested', 'review_started', 'review_completed',
    'review_approved', 'review_rejected', 'issue_resolved'
)
BEGIN
    SELECT 1; -- Allow these new types.
END;

CREATE TRIGGER messages_ad AFTER DELETE ON messages BEGIN
    INSERT INTO messages_fts(messages_fts, rowid, subject, body_md) VALUES('delete', old.id, old.subject, old.body_md);
END;

CREATE TRIGGER messages_ai AFTER INSERT ON messages BEGIN
    INSERT INTO messages_fts(rowid, subject, body_md) VALUES (new.id, new.subject, new.body_md);
END;

CREATE TRIGGER messages_au AFTER UPDATE ON messages BEGIN
    INSERT INTO messages_fts(messages_fts, rowid, subject, body_md) VALUES('delete', old.id, old.subject, old.body_md);
    INSERT INTO messages_fts(rowid, subject, body_md) VALUES (new.id, new.subject, new.body_md);
END;

