-- Agent activity summaries generated by Haiku via Agent SDK.
CREATE TABLE IF NOT EXISTS agent_summaries (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    agent_id INTEGER NOT NULL REFERENCES agents(id),
    summary TEXT NOT NULL,
    delta TEXT NOT NULL DEFAULT '',
    transcript_hash TEXT NOT NULL DEFAULT '',
    cost_usd REAL NOT NULL DEFAULT 0.0,
    created_at INTEGER NOT NULL DEFAULT (unixepoch())
);

CREATE INDEX idx_agent_summaries_agent
    ON agent_summaries(agent_id, created_at DESC);
