// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.0
// source: mail.proto

package subtraterpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Priority represents message priority levels.
type Priority int32

const (
	Priority_PRIORITY_UNSPECIFIED Priority = 0
	Priority_PRIORITY_LOW         Priority = 1
	Priority_PRIORITY_NORMAL      Priority = 2
	Priority_PRIORITY_URGENT      Priority = 3
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_UNSPECIFIED",
		1: "PRIORITY_LOW",
		2: "PRIORITY_NORMAL",
		3: "PRIORITY_URGENT",
	}
	Priority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"PRIORITY_LOW":         1,
		"PRIORITY_NORMAL":      2,
		"PRIORITY_URGENT":      3,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_mail_proto_enumTypes[0].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_mail_proto_enumTypes[0]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{0}
}

// MessageState represents the state of a message for a recipient.
type MessageState int32

const (
	MessageState_STATE_UNSPECIFIED MessageState = 0
	MessageState_STATE_UNREAD      MessageState = 1
	MessageState_STATE_READ        MessageState = 2
	MessageState_STATE_STARRED     MessageState = 3
	MessageState_STATE_SNOOZED     MessageState = 4
	MessageState_STATE_ARCHIVED    MessageState = 5
	MessageState_STATE_TRASH       MessageState = 6
)

// Enum value maps for MessageState.
var (
	MessageState_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_UNREAD",
		2: "STATE_READ",
		3: "STATE_STARRED",
		4: "STATE_SNOOZED",
		5: "STATE_ARCHIVED",
		6: "STATE_TRASH",
	}
	MessageState_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_UNREAD":      1,
		"STATE_READ":        2,
		"STATE_STARRED":     3,
		"STATE_SNOOZED":     4,
		"STATE_ARCHIVED":    5,
		"STATE_TRASH":       6,
	}
)

func (x MessageState) Enum() *MessageState {
	p := new(MessageState)
	*p = x
	return p
}

func (x MessageState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageState) Descriptor() protoreflect.EnumDescriptor {
	return file_mail_proto_enumTypes[1].Descriptor()
}

func (MessageState) Type() protoreflect.EnumType {
	return &file_mail_proto_enumTypes[1]
}

func (x MessageState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageState.Descriptor instead.
func (MessageState) EnumDescriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{1}
}

// InboxMessage represents a message in an agent's inbox.
type InboxMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ThreadId      string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	TopicId       int64                  `protobuf:"varint,3,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	SenderId      int64                  `protobuf:"varint,4,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderName    string                 `protobuf:"bytes,5,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	Subject       string                 `protobuf:"bytes,6,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	Priority      Priority               `protobuf:"varint,8,opt,name=priority,proto3,enum=subtraterpc.Priority" json:"priority,omitempty"`
	State         MessageState           `protobuf:"varint,9,opt,name=state,proto3,enum=subtraterpc.MessageState" json:"state,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`          // Unix timestamp
	DeadlineAt    int64                  `protobuf:"varint,11,opt,name=deadline_at,json=deadlineAt,proto3" json:"deadline_at,omitempty"`       // Unix timestamp, 0 if no deadline
	SnoozedUntil  int64                  `protobuf:"varint,12,opt,name=snoozed_until,json=snoozedUntil,proto3" json:"snoozed_until,omitempty"` // Unix timestamp, 0 if not snoozed
	ReadAt        int64                  `protobuf:"varint,13,opt,name=read_at,json=readAt,proto3" json:"read_at,omitempty"`                   // Unix timestamp, 0 if unread
	AckedAt       int64                  `protobuf:"varint,14,opt,name=acked_at,json=ackedAt,proto3" json:"acked_at,omitempty"`                // Unix timestamp, 0 if not acked
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboxMessage) Reset() {
	*x = InboxMessage{}
	mi := &file_mail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboxMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboxMessage) ProtoMessage() {}

func (x *InboxMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboxMessage.ProtoReflect.Descriptor instead.
func (*InboxMessage) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{0}
}

func (x *InboxMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InboxMessage) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *InboxMessage) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *InboxMessage) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *InboxMessage) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *InboxMessage) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *InboxMessage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *InboxMessage) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *InboxMessage) GetState() MessageState {
	if x != nil {
		return x.State
	}
	return MessageState_STATE_UNSPECIFIED
}

func (x *InboxMessage) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *InboxMessage) GetDeadlineAt() int64 {
	if x != nil {
		return x.DeadlineAt
	}
	return 0
}

func (x *InboxMessage) GetSnoozedUntil() int64 {
	if x != nil {
		return x.SnoozedUntil
	}
	return 0
}

func (x *InboxMessage) GetReadAt() int64 {
	if x != nil {
		return x.ReadAt
	}
	return 0
}

func (x *InboxMessage) GetAckedAt() int64 {
	if x != nil {
		return x.AckedAt
	}
	return 0
}

// SendMailRequest is the request for SendMail.
type SendMailRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SenderId        int64                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	RecipientNames  []string               `protobuf:"bytes,2,rep,name=recipient_names,json=recipientNames,proto3" json:"recipient_names,omitempty"`
	TopicName       string                 `protobuf:"bytes,3,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"` // For pub/sub, mutually exclusive with recipients
	ThreadId        string                 `protobuf:"bytes,4,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`    // Optional, for replies
	Subject         string                 `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	Body            string                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	Priority        Priority               `protobuf:"varint,7,opt,name=priority,proto3,enum=subtraterpc.Priority" json:"priority,omitempty"`
	DeadlineAt      int64                  `protobuf:"varint,8,opt,name=deadline_at,json=deadlineAt,proto3" json:"deadline_at,omitempty"`               // Unix timestamp, 0 for no deadline
	AttachmentsJson string                 `protobuf:"bytes,9,opt,name=attachments_json,json=attachmentsJson,proto3" json:"attachments_json,omitempty"` // JSON string of attachments
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SendMailRequest) Reset() {
	*x = SendMailRequest{}
	mi := &file_mail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMailRequest) ProtoMessage() {}

func (x *SendMailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMailRequest.ProtoReflect.Descriptor instead.
func (*SendMailRequest) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{1}
}

func (x *SendMailRequest) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *SendMailRequest) GetRecipientNames() []string {
	if x != nil {
		return x.RecipientNames
	}
	return nil
}

func (x *SendMailRequest) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *SendMailRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *SendMailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendMailRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SendMailRequest) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

func (x *SendMailRequest) GetDeadlineAt() int64 {
	if x != nil {
		return x.DeadlineAt
	}
	return 0
}

func (x *SendMailRequest) GetAttachmentsJson() string {
	if x != nil {
		return x.AttachmentsJson
	}
	return ""
}

// SendMailResponse is the response for SendMail.
type SendMailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ThreadId      string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMailResponse) Reset() {
	*x = SendMailResponse{}
	mi := &file_mail_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMailResponse) ProtoMessage() {}

func (x *SendMailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMailResponse.ProtoReflect.Descriptor instead.
func (*SendMailResponse) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{2}
}

func (x *SendMailResponse) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *SendMailResponse) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

// FetchInboxRequest is the request for FetchInbox.
type FetchInboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       int64                  `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                                                              // Maximum messages to return
	UnreadOnly    bool                   `protobuf:"varint,3,opt,name=unread_only,json=unreadOnly,proto3" json:"unread_only,omitempty"`                                  // Only return unread messages
	StateFilter   MessageState           `protobuf:"varint,4,opt,name=state_filter,json=stateFilter,proto3,enum=subtraterpc.MessageState" json:"state_filter,omitempty"` // Filter by state
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchInboxRequest) Reset() {
	*x = FetchInboxRequest{}
	mi := &file_mail_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchInboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchInboxRequest) ProtoMessage() {}

func (x *FetchInboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchInboxRequest.ProtoReflect.Descriptor instead.
func (*FetchInboxRequest) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{3}
}

func (x *FetchInboxRequest) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *FetchInboxRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FetchInboxRequest) GetUnreadOnly() bool {
	if x != nil {
		return x.UnreadOnly
	}
	return false
}

func (x *FetchInboxRequest) GetStateFilter() MessageState {
	if x != nil {
		return x.StateFilter
	}
	return MessageState_STATE_UNSPECIFIED
}

// FetchInboxResponse is the response for FetchInbox.
type FetchInboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*InboxMessage        `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchInboxResponse) Reset() {
	*x = FetchInboxResponse{}
	mi := &file_mail_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchInboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchInboxResponse) ProtoMessage() {}

func (x *FetchInboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchInboxResponse.ProtoReflect.Descriptor instead.
func (*FetchInboxResponse) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{4}
}

func (x *FetchInboxResponse) GetMessages() []*InboxMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

// ReadMessageRequest is the request for ReadMessage.
type ReadMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       int64                  `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	MessageId     int64                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadMessageRequest) Reset() {
	*x = ReadMessageRequest{}
	mi := &file_mail_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMessageRequest) ProtoMessage() {}

func (x *ReadMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMessageRequest.ProtoReflect.Descriptor instead.
func (*ReadMessageRequest) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{5}
}

func (x *ReadMessageRequest) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *ReadMessageRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

// ReadMessageResponse is the response for ReadMessage.
type ReadMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *InboxMessage          `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadMessageResponse) Reset() {
	*x = ReadMessageResponse{}
	mi := &file_mail_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMessageResponse) ProtoMessage() {}

func (x *ReadMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMessageResponse.ProtoReflect.Descriptor instead.
func (*ReadMessageResponse) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{6}
}

func (x *ReadMessageResponse) GetMessage() *InboxMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

// ReadThreadRequest is the request for ReadThread.
type ReadThreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       int64                  `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ThreadId      string                 `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadThreadRequest) Reset() {
	*x = ReadThreadRequest{}
	mi := &file_mail_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadThreadRequest) ProtoMessage() {}

func (x *ReadThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadThreadRequest.ProtoReflect.Descriptor instead.
func (*ReadThreadRequest) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{7}
}

func (x *ReadThreadRequest) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *ReadThreadRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

// ReadThreadResponse is the response for ReadThread.
type ReadThreadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*InboxMessage        `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadThreadResponse) Reset() {
	*x = ReadThreadResponse{}
	mi := &file_mail_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadThreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadThreadResponse) ProtoMessage() {}

func (x *ReadThreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadThreadResponse.ProtoReflect.Descriptor instead.
func (*ReadThreadResponse) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{8}
}

func (x *ReadThreadResponse) GetMessages() []*InboxMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

// UpdateStateRequest is the request for UpdateState.
type UpdateStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       int64                  `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	MessageId     int64                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	NewState      MessageState           `protobuf:"varint,3,opt,name=new_state,json=newState,proto3,enum=subtraterpc.MessageState" json:"new_state,omitempty"`
	SnoozedUntil  int64                  `protobuf:"varint,4,opt,name=snoozed_until,json=snoozedUntil,proto3" json:"snoozed_until,omitempty"` // Required for STATE_SNOOZED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStateRequest) Reset() {
	*x = UpdateStateRequest{}
	mi := &file_mail_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStateRequest) ProtoMessage() {}

func (x *UpdateStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStateRequest.ProtoReflect.Descriptor instead.
func (*UpdateStateRequest) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateStateRequest) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *UpdateStateRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *UpdateStateRequest) GetNewState() MessageState {
	if x != nil {
		return x.NewState
	}
	return MessageState_STATE_UNSPECIFIED
}

func (x *UpdateStateRequest) GetSnoozedUntil() int64 {
	if x != nil {
		return x.SnoozedUntil
	}
	return 0
}

// UpdateStateResponse is the response for UpdateState.
type UpdateStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStateResponse) Reset() {
	*x = UpdateStateResponse{}
	mi := &file_mail_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStateResponse) ProtoMessage() {}

func (x *UpdateStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStateResponse.ProtoReflect.Descriptor instead.
func (*UpdateStateResponse) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateStateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// AckMessageRequest is the request for AckMessage.
type AckMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       int64                  `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	MessageId     int64                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckMessageRequest) Reset() {
	*x = AckMessageRequest{}
	mi := &file_mail_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMessageRequest) ProtoMessage() {}

func (x *AckMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMessageRequest.ProtoReflect.Descriptor instead.
func (*AckMessageRequest) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{11}
}

func (x *AckMessageRequest) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *AckMessageRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

// AckMessageResponse is the response for AckMessage.
type AckMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckMessageResponse) Reset() {
	*x = AckMessageResponse{}
	mi := &file_mail_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMessageResponse) ProtoMessage() {}

func (x *AckMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMessageResponse.ProtoReflect.Descriptor instead.
func (*AckMessageResponse) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{12}
}

func (x *AckMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// GetStatusRequest is the request for GetStatus.
type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       int64                  `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_mail_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{13}
}

func (x *GetStatusRequest) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

// GetStatusResponse is the response for GetStatus.
type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       int64                  `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentName     string                 `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	UnreadCount   int64                  `protobuf:"varint,3,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	UrgentCount   int64                  `protobuf:"varint,4,opt,name=urgent_count,json=urgentCount,proto3" json:"urgent_count,omitempty"`
	StarredCount  int64                  `protobuf:"varint,5,opt,name=starred_count,json=starredCount,proto3" json:"starred_count,omitempty"`
	SnoozedCount  int64                  `protobuf:"varint,6,opt,name=snoozed_count,json=snoozedCount,proto3" json:"snoozed_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_mail_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{14}
}

func (x *GetStatusResponse) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *GetStatusResponse) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *GetStatusResponse) GetUnreadCount() int64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *GetStatusResponse) GetUrgentCount() int64 {
	if x != nil {
		return x.UrgentCount
	}
	return 0
}

func (x *GetStatusResponse) GetStarredCount() int64 {
	if x != nil {
		return x.StarredCount
	}
	return 0
}

func (x *GetStatusResponse) GetSnoozedCount() int64 {
	if x != nil {
		return x.SnoozedCount
	}
	return 0
}

// PollChangesRequest is the request for PollChanges.
type PollChangesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       int64                  `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SinceOffsets  map[int64]int64        `protobuf:"bytes,2,rep,name=since_offsets,json=sinceOffsets,proto3" json:"since_offsets,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // topic_id -> last_offset
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollChangesRequest) Reset() {
	*x = PollChangesRequest{}
	mi := &file_mail_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollChangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollChangesRequest) ProtoMessage() {}

func (x *PollChangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollChangesRequest.ProtoReflect.Descriptor instead.
func (*PollChangesRequest) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{15}
}

func (x *PollChangesRequest) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *PollChangesRequest) GetSinceOffsets() map[int64]int64 {
	if x != nil {
		return x.SinceOffsets
	}
	return nil
}

// PollChangesResponse is the response for PollChanges.
type PollChangesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewMessages   []*InboxMessage        `protobuf:"bytes,1,rep,name=new_messages,json=newMessages,proto3" json:"new_messages,omitempty"`
	NewOffsets    map[int64]int64        `protobuf:"bytes,2,rep,name=new_offsets,json=newOffsets,proto3" json:"new_offsets,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // topic_id -> new_offset
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollChangesResponse) Reset() {
	*x = PollChangesResponse{}
	mi := &file_mail_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollChangesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollChangesResponse) ProtoMessage() {}

func (x *PollChangesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollChangesResponse.ProtoReflect.Descriptor instead.
func (*PollChangesResponse) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{16}
}

func (x *PollChangesResponse) GetNewMessages() []*InboxMessage {
	if x != nil {
		return x.NewMessages
	}
	return nil
}

func (x *PollChangesResponse) GetNewOffsets() map[int64]int64 {
	if x != nil {
		return x.NewOffsets
	}
	return nil
}

// SubscribeInboxRequest is the request for SubscribeInbox streaming.
type SubscribeInboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       int64                  `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeInboxRequest) Reset() {
	*x = SubscribeInboxRequest{}
	mi := &file_mail_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeInboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeInboxRequest) ProtoMessage() {}

func (x *SubscribeInboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeInboxRequest.ProtoReflect.Descriptor instead.
func (*SubscribeInboxRequest) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{17}
}

func (x *SubscribeInboxRequest) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

// PublishRequest is the request for Publish.
type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      int64                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	TopicName     string                 `protobuf:"bytes,2,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Priority      Priority               `protobuf:"varint,5,opt,name=priority,proto3,enum=subtraterpc.Priority" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_mail_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{18}
}

func (x *PublishRequest) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *PublishRequest) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *PublishRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *PublishRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *PublishRequest) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

// PublishResponse is the response for Publish.
type PublishResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MessageId       int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	RecipientsCount int32                  `protobuf:"varint,2,opt,name=recipients_count,json=recipientsCount,proto3" json:"recipients_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_mail_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{19}
}

func (x *PublishResponse) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *PublishResponse) GetRecipientsCount() int32 {
	if x != nil {
		return x.RecipientsCount
	}
	return 0
}

// SubscribeRequest is the request for Subscribe.
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       int64                  `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TopicName     string                 `protobuf:"bytes,2,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_mail_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{20}
}

func (x *SubscribeRequest) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *SubscribeRequest) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

// SubscribeResponse is the response for Subscribe.
type SubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TopicId       int64                  `protobuf:"varint,2,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_mail_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{21}
}

func (x *SubscribeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubscribeResponse) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

// UnsubscribeRequest is the request for Unsubscribe.
type UnsubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       int64                  `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TopicName     string                 `protobuf:"bytes,2,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeRequest) Reset() {
	*x = UnsubscribeRequest{}
	mi := &file_mail_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeRequest) ProtoMessage() {}

func (x *UnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{22}
}

func (x *UnsubscribeRequest) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *UnsubscribeRequest) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

// UnsubscribeResponse is the response for Unsubscribe.
type UnsubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeResponse) Reset() {
	*x = UnsubscribeResponse{}
	mi := &file_mail_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeResponse) ProtoMessage() {}

func (x *UnsubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeResponse.ProtoReflect.Descriptor instead.
func (*UnsubscribeResponse) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{23}
}

func (x *UnsubscribeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Topic represents a pub/sub topic.
type Topic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TopicType     string                 `protobuf:"bytes,3,opt,name=topic_type,json=topicType,proto3" json:"topic_type,omitempty"` // "direct", "broadcast", "queue"
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topic) Reset() {
	*x = Topic{}
	mi := &file_mail_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic) ProtoMessage() {}

func (x *Topic) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic.ProtoReflect.Descriptor instead.
func (*Topic) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{24}
}

func (x *Topic) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Topic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Topic) GetTopicType() string {
	if x != nil {
		return x.TopicType
	}
	return ""
}

func (x *Topic) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// ListTopicsRequest is the request for ListTopics.
type ListTopicsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        int64                  `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // If set, only show subscribed topics
	SubscribedOnly bool                   `protobuf:"varint,2,opt,name=subscribed_only,json=subscribedOnly,proto3" json:"subscribed_only,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListTopicsRequest) Reset() {
	*x = ListTopicsRequest{}
	mi := &file_mail_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopicsRequest) ProtoMessage() {}

func (x *ListTopicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopicsRequest.ProtoReflect.Descriptor instead.
func (*ListTopicsRequest) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{25}
}

func (x *ListTopicsRequest) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *ListTopicsRequest) GetSubscribedOnly() bool {
	if x != nil {
		return x.SubscribedOnly
	}
	return false
}

// ListTopicsResponse is the response for ListTopics.
type ListTopicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []*Topic               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopicsResponse) Reset() {
	*x = ListTopicsResponse{}
	mi := &file_mail_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopicsResponse) ProtoMessage() {}

func (x *ListTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopicsResponse.ProtoReflect.Descriptor instead.
func (*ListTopicsResponse) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{26}
}

func (x *ListTopicsResponse) GetTopics() []*Topic {
	if x != nil {
		return x.Topics
	}
	return nil
}

// SearchRequest is the request for Search.
type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       int64                  `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	TopicId       int64                  `protobuf:"varint,3,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"` // Optional, filter by topic
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_mail_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{27}
}

func (x *SearchRequest) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// SearchResponse is the response for Search.
type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*InboxMessage        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_mail_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{28}
}

func (x *SearchResponse) GetResults() []*InboxMessage {
	if x != nil {
		return x.Results
	}
	return nil
}

// HasUnackedStatusToRequest is the request for HasUnackedStatusTo.
type HasUnackedStatusToRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      int64                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	RecipientId   int64                  `protobuf:"varint,2,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasUnackedStatusToRequest) Reset() {
	*x = HasUnackedStatusToRequest{}
	mi := &file_mail_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasUnackedStatusToRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasUnackedStatusToRequest) ProtoMessage() {}

func (x *HasUnackedStatusToRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasUnackedStatusToRequest.ProtoReflect.Descriptor instead.
func (*HasUnackedStatusToRequest) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{29}
}

func (x *HasUnackedStatusToRequest) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *HasUnackedStatusToRequest) GetRecipientId() int64 {
	if x != nil {
		return x.RecipientId
	}
	return 0
}

// HasUnackedStatusToResponse is the response for HasUnackedStatusTo.
type HasUnackedStatusToResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasPending    bool                   `protobuf:"varint,1,opt,name=has_pending,json=hasPending,proto3" json:"has_pending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasUnackedStatusToResponse) Reset() {
	*x = HasUnackedStatusToResponse{}
	mi := &file_mail_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasUnackedStatusToResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasUnackedStatusToResponse) ProtoMessage() {}

func (x *HasUnackedStatusToResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasUnackedStatusToResponse.ProtoReflect.Descriptor instead.
func (*HasUnackedStatusToResponse) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{30}
}

func (x *HasUnackedStatusToResponse) GetHasPending() bool {
	if x != nil {
		return x.HasPending
	}
	return false
}

// RegisterAgentRequest is the request for RegisterAgent.
type RegisterAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ProjectKey    string                 `protobuf:"bytes,2,opt,name=project_key,json=projectKey,proto3" json:"project_key,omitempty"` // Optional project binding
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_mail_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{31}
}

func (x *RegisterAgentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterAgentRequest) GetProjectKey() string {
	if x != nil {
		return x.ProjectKey
	}
	return ""
}

// RegisterAgentResponse is the response for RegisterAgent.
type RegisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       int64                  `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentResponse) Reset() {
	*x = RegisterAgentResponse{}
	mi := &file_mail_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentResponse) ProtoMessage() {}

func (x *RegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{32}
}

func (x *RegisterAgentResponse) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *RegisterAgentResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GetAgentRequest is the request for GetAgent.
type GetAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       int64                  `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // Use ID or name
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_mail_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{33}
}

func (x *GetAgentRequest) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *GetAgentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GetAgentResponse is the response for GetAgent.
type GetAgentResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProjectKey       string                 `protobuf:"bytes,3,opt,name=project_key,json=projectKey,proto3" json:"project_key,omitempty"`
	CurrentSessionId string                 `protobuf:"bytes,4,opt,name=current_session_id,json=currentSessionId,proto3" json:"current_session_id,omitempty"`
	CreatedAt        int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastActiveAt     int64                  `protobuf:"varint,6,opt,name=last_active_at,json=lastActiveAt,proto3" json:"last_active_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetAgentResponse) Reset() {
	*x = GetAgentResponse{}
	mi := &file_mail_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentResponse) ProtoMessage() {}

func (x *GetAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentResponse.ProtoReflect.Descriptor instead.
func (*GetAgentResponse) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{34}
}

func (x *GetAgentResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetAgentResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetAgentResponse) GetProjectKey() string {
	if x != nil {
		return x.ProjectKey
	}
	return ""
}

func (x *GetAgentResponse) GetCurrentSessionId() string {
	if x != nil {
		return x.CurrentSessionId
	}
	return ""
}

func (x *GetAgentResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GetAgentResponse) GetLastActiveAt() int64 {
	if x != nil {
		return x.LastActiveAt
	}
	return 0
}

// ListAgentsRequest is the request for ListAgents.
type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_mail_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{35}
}

func (x *ListAgentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListAgentsResponse is the response for ListAgents.
type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*GetAgentResponse    `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_mail_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{36}
}

func (x *ListAgentsResponse) GetAgents() []*GetAgentResponse {
	if x != nil {
		return x.Agents
	}
	return nil
}

// EnsureIdentityRequest is the request for EnsureIdentity.
type EnsureIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ProjectDir    string                 `protobuf:"bytes,2,opt,name=project_dir,json=projectDir,proto3" json:"project_dir,omitempty"`
	GitBranch     string                 `protobuf:"bytes,3,opt,name=git_branch,json=gitBranch,proto3" json:"git_branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureIdentityRequest) Reset() {
	*x = EnsureIdentityRequest{}
	mi := &file_mail_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureIdentityRequest) ProtoMessage() {}

func (x *EnsureIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureIdentityRequest.ProtoReflect.Descriptor instead.
func (*EnsureIdentityRequest) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{37}
}

func (x *EnsureIdentityRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EnsureIdentityRequest) GetProjectDir() string {
	if x != nil {
		return x.ProjectDir
	}
	return ""
}

func (x *EnsureIdentityRequest) GetGitBranch() string {
	if x != nil {
		return x.GitBranch
	}
	return ""
}

// EnsureIdentityResponse is the response for EnsureIdentity.
type EnsureIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       int64                  `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentName     string                 `protobuf:"bytes,2,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	Created       bool                   `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"` // True if a new agent was created
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureIdentityResponse) Reset() {
	*x = EnsureIdentityResponse{}
	mi := &file_mail_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureIdentityResponse) ProtoMessage() {}

func (x *EnsureIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureIdentityResponse.ProtoReflect.Descriptor instead.
func (*EnsureIdentityResponse) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{38}
}

func (x *EnsureIdentityResponse) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *EnsureIdentityResponse) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *EnsureIdentityResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

// SaveIdentityRequest is the request for SaveIdentity.
type SaveIdentityRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AgentId         int64                  `protobuf:"varint,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ConsumerOffsets map[int64]int64        `protobuf:"bytes,3,rep,name=consumer_offsets,json=consumerOffsets,proto3" json:"consumer_offsets,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // topic_id -> offset
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SaveIdentityRequest) Reset() {
	*x = SaveIdentityRequest{}
	mi := &file_mail_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveIdentityRequest) ProtoMessage() {}

func (x *SaveIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveIdentityRequest.ProtoReflect.Descriptor instead.
func (*SaveIdentityRequest) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{39}
}

func (x *SaveIdentityRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SaveIdentityRequest) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *SaveIdentityRequest) GetConsumerOffsets() map[int64]int64 {
	if x != nil {
		return x.ConsumerOffsets
	}
	return nil
}

// SaveIdentityResponse is the response for SaveIdentity.
type SaveIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveIdentityResponse) Reset() {
	*x = SaveIdentityResponse{}
	mi := &file_mail_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveIdentityResponse) ProtoMessage() {}

func (x *SaveIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveIdentityResponse.ProtoReflect.Descriptor instead.
func (*SaveIdentityResponse) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{40}
}

func (x *SaveIdentityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// DeleteAgentRequest is the request for DeleteAgent.
type DeleteAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAgentRequest) Reset() {
	*x = DeleteAgentRequest{}
	mi := &file_mail_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentRequest) ProtoMessage() {}

func (x *DeleteAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentRequest.ProtoReflect.Descriptor instead.
func (*DeleteAgentRequest) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{41}
}

func (x *DeleteAgentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// DeleteAgentResponse is the response for DeleteAgent.
type DeleteAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAgentResponse) Reset() {
	*x = DeleteAgentResponse{}
	mi := &file_mail_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentResponse) ProtoMessage() {}

func (x *DeleteAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mail_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentResponse.ProtoReflect.Descriptor instead.
func (*DeleteAgentResponse) Descriptor() ([]byte, []int) {
	return file_mail_proto_rawDescGZIP(), []int{42}
}

func (x *DeleteAgentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_mail_proto protoreflect.FileDescriptor

const file_mail_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"mail.proto\x12\vsubtraterpc\"\xbf\x03\n" +
	"\fInboxMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\x12\x19\n" +
	"\btopic_id\x18\x03 \x01(\x03R\atopicId\x12\x1b\n" +
	"\tsender_id\x18\x04 \x01(\x03R\bsenderId\x12\x1f\n" +
	"\vsender_name\x18\x05 \x01(\tR\n" +
	"senderName\x12\x18\n" +
	"\asubject\x18\x06 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\a \x01(\tR\x04body\x121\n" +
	"\bpriority\x18\b \x01(\x0e2\x15.subtraterpc.PriorityR\bpriority\x12/\n" +
	"\x05state\x18\t \x01(\x0e2\x19.subtraterpc.MessageStateR\x05state\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1f\n" +
	"\vdeadline_at\x18\v \x01(\x03R\n" +
	"deadlineAt\x12#\n" +
	"\rsnoozed_until\x18\f \x01(\x03R\fsnoozedUntil\x12\x17\n" +
	"\aread_at\x18\r \x01(\x03R\x06readAt\x12\x19\n" +
	"\backed_at\x18\x0e \x01(\x03R\aackedAt\"\xc0\x02\n" +
	"\x0fSendMailRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x03R\bsenderId\x12'\n" +
	"\x0frecipient_names\x18\x02 \x03(\tR\x0erecipientNames\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x03 \x01(\tR\ttopicName\x12\x1b\n" +
	"\tthread_id\x18\x04 \x01(\tR\bthreadId\x12\x18\n" +
	"\asubject\x18\x05 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x06 \x01(\tR\x04body\x121\n" +
	"\bpriority\x18\a \x01(\x0e2\x15.subtraterpc.PriorityR\bpriority\x12\x1f\n" +
	"\vdeadline_at\x18\b \x01(\x03R\n" +
	"deadlineAt\x12)\n" +
	"\x10attachments_json\x18\t \x01(\tR\x0fattachmentsJson\"N\n" +
	"\x10SendMailResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\"\xa3\x01\n" +
	"\x11FetchInboxRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x03R\aagentId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1f\n" +
	"\vunread_only\x18\x03 \x01(\bR\n" +
	"unreadOnly\x12<\n" +
	"\fstate_filter\x18\x04 \x01(\x0e2\x19.subtraterpc.MessageStateR\vstateFilter\"K\n" +
	"\x12FetchInboxResponse\x125\n" +
	"\bmessages\x18\x01 \x03(\v2\x19.subtraterpc.InboxMessageR\bmessages\"N\n" +
	"\x12ReadMessageRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x03R\aagentId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\"J\n" +
	"\x13ReadMessageResponse\x123\n" +
	"\amessage\x18\x01 \x01(\v2\x19.subtraterpc.InboxMessageR\amessage\"K\n" +
	"\x11ReadThreadRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x03R\aagentId\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\"K\n" +
	"\x12ReadThreadResponse\x125\n" +
	"\bmessages\x18\x01 \x03(\v2\x19.subtraterpc.InboxMessageR\bmessages\"\xab\x01\n" +
	"\x12UpdateStateRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x03R\aagentId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\x126\n" +
	"\tnew_state\x18\x03 \x01(\x0e2\x19.subtraterpc.MessageStateR\bnewState\x12#\n" +
	"\rsnoozed_until\x18\x04 \x01(\x03R\fsnoozedUntil\"/\n" +
	"\x13UpdateStateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"M\n" +
	"\x11AckMessageRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x03R\aagentId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\".\n" +
	"\x12AckMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"-\n" +
	"\x10GetStatusRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x03R\aagentId\"\xdd\x01\n" +
	"\x11GetStatusResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x03R\aagentId\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x02 \x01(\tR\tagentName\x12!\n" +
	"\funread_count\x18\x03 \x01(\x03R\vunreadCount\x12!\n" +
	"\furgent_count\x18\x04 \x01(\x03R\vurgentCount\x12#\n" +
	"\rstarred_count\x18\x05 \x01(\x03R\fstarredCount\x12#\n" +
	"\rsnoozed_count\x18\x06 \x01(\x03R\fsnoozedCount\"\xc8\x01\n" +
	"\x12PollChangesRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x03R\aagentId\x12V\n" +
	"\rsince_offsets\x18\x02 \x03(\v21.subtraterpc.PollChangesRequest.SinceOffsetsEntryR\fsinceOffsets\x1a?\n" +
	"\x11SinceOffsetsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xe5\x01\n" +
	"\x13PollChangesResponse\x12<\n" +
	"\fnew_messages\x18\x01 \x03(\v2\x19.subtraterpc.InboxMessageR\vnewMessages\x12Q\n" +
	"\vnew_offsets\x18\x02 \x03(\v20.subtraterpc.PollChangesResponse.NewOffsetsEntryR\n" +
	"newOffsets\x1a=\n" +
	"\x0fNewOffsetsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"2\n" +
	"\x15SubscribeInboxRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x03R\aagentId\"\xad\x01\n" +
	"\x0ePublishRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x03R\bsenderId\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x02 \x01(\tR\ttopicName\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x121\n" +
	"\bpriority\x18\x05 \x01(\x0e2\x15.subtraterpc.PriorityR\bpriority\"[\n" +
	"\x0fPublishResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12)\n" +
	"\x10recipients_count\x18\x02 \x01(\x05R\x0frecipientsCount\"L\n" +
	"\x10SubscribeRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x03R\aagentId\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x02 \x01(\tR\ttopicName\"H\n" +
	"\x11SubscribeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\btopic_id\x18\x02 \x01(\x03R\atopicId\"N\n" +
	"\x12UnsubscribeRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x03R\aagentId\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x02 \x01(\tR\ttopicName\"/\n" +
	"\x13UnsubscribeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"i\n" +
	"\x05Topic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"topic_type\x18\x03 \x01(\tR\ttopicType\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\"W\n" +
	"\x11ListTopicsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x03R\aagentId\x12'\n" +
	"\x0fsubscribed_only\x18\x02 \x01(\bR\x0esubscribedOnly\"@\n" +
	"\x12ListTopicsResponse\x12*\n" +
	"\x06topics\x18\x01 \x03(\v2\x12.subtraterpc.TopicR\x06topics\"q\n" +
	"\rSearchRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x03R\aagentId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x19\n" +
	"\btopic_id\x18\x03 \x01(\x03R\atopicId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"E\n" +
	"\x0eSearchResponse\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.subtraterpc.InboxMessageR\aresults\"[\n" +
	"\x19HasUnackedStatusToRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x03R\bsenderId\x12!\n" +
	"\frecipient_id\x18\x02 \x01(\x03R\vrecipientId\"=\n" +
	"\x1aHasUnackedStatusToResponse\x12\x1f\n" +
	"\vhas_pending\x18\x01 \x01(\bR\n" +
	"hasPending\"K\n" +
	"\x14RegisterAgentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vproject_key\x18\x02 \x01(\tR\n" +
	"projectKey\"F\n" +
	"\x15RegisterAgentResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x03R\aagentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"@\n" +
	"\x0fGetAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x03R\aagentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xca\x01\n" +
	"\x10GetAgentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vproject_key\x18\x03 \x01(\tR\n" +
	"projectKey\x12,\n" +
	"\x12current_session_id\x18\x04 \x01(\tR\x10currentSessionId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12$\n" +
	"\x0elast_active_at\x18\x06 \x01(\x03R\flastActiveAt\")\n" +
	"\x11ListAgentsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"K\n" +
	"\x12ListAgentsResponse\x125\n" +
	"\x06agents\x18\x01 \x03(\v2\x1d.subtraterpc.GetAgentResponseR\x06agents\"v\n" +
	"\x15EnsureIdentityRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vproject_dir\x18\x02 \x01(\tR\n" +
	"projectDir\x12\x1d\n" +
	"\n" +
	"git_branch\x18\x03 \x01(\tR\tgitBranch\"l\n" +
	"\x16EnsureIdentityResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x03R\aagentId\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x02 \x01(\tR\tagentName\x12\x18\n" +
	"\acreated\x18\x03 \x01(\bR\acreated\"\xf5\x01\n" +
	"\x13SaveIdentityRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\x03R\aagentId\x12`\n" +
	"\x10consumer_offsets\x18\x03 \x03(\v25.subtraterpc.SaveIdentityRequest.ConsumerOffsetsEntryR\x0fconsumerOffsets\x1aB\n" +
	"\x14ConsumerOffsetsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"0\n" +
	"\x14SaveIdentityResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"$\n" +
	"\x12DeleteAgentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"/\n" +
	"\x13DeleteAgentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*`\n" +
	"\bPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPRIORITY_LOW\x10\x01\x12\x13\n" +
	"\x0fPRIORITY_NORMAL\x10\x02\x12\x13\n" +
	"\x0fPRIORITY_URGENT\x10\x03*\x92\x01\n" +
	"\fMessageState\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fSTATE_UNREAD\x10\x01\x12\x0e\n" +
	"\n" +
	"STATE_READ\x10\x02\x12\x11\n" +
	"\rSTATE_STARRED\x10\x03\x12\x11\n" +
	"\rSTATE_SNOOZED\x10\x04\x12\x12\n" +
	"\x0eSTATE_ARCHIVED\x10\x05\x12\x0f\n" +
	"\vSTATE_TRASH\x10\x062\xae\t\n" +
	"\x04Mail\x12G\n" +
	"\bSendMail\x12\x1c.subtraterpc.SendMailRequest\x1a\x1d.subtraterpc.SendMailResponse\x12M\n" +
	"\n" +
	"FetchInbox\x12\x1e.subtraterpc.FetchInboxRequest\x1a\x1f.subtraterpc.FetchInboxResponse\x12P\n" +
	"\vReadMessage\x12\x1f.subtraterpc.ReadMessageRequest\x1a .subtraterpc.ReadMessageResponse\x12M\n" +
	"\n" +
	"ReadThread\x12\x1e.subtraterpc.ReadThreadRequest\x1a\x1f.subtraterpc.ReadThreadResponse\x12P\n" +
	"\vUpdateState\x12\x1f.subtraterpc.UpdateStateRequest\x1a .subtraterpc.UpdateStateResponse\x12M\n" +
	"\n" +
	"AckMessage\x12\x1e.subtraterpc.AckMessageRequest\x1a\x1f.subtraterpc.AckMessageResponse\x12J\n" +
	"\tGetStatus\x12\x1d.subtraterpc.GetStatusRequest\x1a\x1e.subtraterpc.GetStatusResponse\x12P\n" +
	"\vPollChanges\x12\x1f.subtraterpc.PollChangesRequest\x1a .subtraterpc.PollChangesResponse\x12Q\n" +
	"\x0eSubscribeInbox\x12\".subtraterpc.SubscribeInboxRequest\x1a\x19.subtraterpc.InboxMessage0\x01\x12D\n" +
	"\aPublish\x12\x1b.subtraterpc.PublishRequest\x1a\x1c.subtraterpc.PublishResponse\x12J\n" +
	"\tSubscribe\x12\x1d.subtraterpc.SubscribeRequest\x1a\x1e.subtraterpc.SubscribeResponse\x12P\n" +
	"\vUnsubscribe\x12\x1f.subtraterpc.UnsubscribeRequest\x1a .subtraterpc.UnsubscribeResponse\x12M\n" +
	"\n" +
	"ListTopics\x12\x1e.subtraterpc.ListTopicsRequest\x1a\x1f.subtraterpc.ListTopicsResponse\x12A\n" +
	"\x06Search\x12\x1a.subtraterpc.SearchRequest\x1a\x1b.subtraterpc.SearchResponse\x12e\n" +
	"\x12HasUnackedStatusTo\x12&.subtraterpc.HasUnackedStatusToRequest\x1a'.subtraterpc.HasUnackedStatusToResponse2\xf9\x03\n" +
	"\x05Agent\x12V\n" +
	"\rRegisterAgent\x12!.subtraterpc.RegisterAgentRequest\x1a\".subtraterpc.RegisterAgentResponse\x12G\n" +
	"\bGetAgent\x12\x1c.subtraterpc.GetAgentRequest\x1a\x1d.subtraterpc.GetAgentResponse\x12M\n" +
	"\n" +
	"ListAgents\x12\x1e.subtraterpc.ListAgentsRequest\x1a\x1f.subtraterpc.ListAgentsResponse\x12P\n" +
	"\vDeleteAgent\x12\x1f.subtraterpc.DeleteAgentRequest\x1a .subtraterpc.DeleteAgentResponse\x12Y\n" +
	"\x0eEnsureIdentity\x12\".subtraterpc.EnsureIdentityRequest\x1a#.subtraterpc.EnsureIdentityResponse\x12S\n" +
	"\fSaveIdentity\x12 .subtraterpc.SaveIdentityRequest\x1a!.subtraterpc.SaveIdentityResponseB<Z:github.com/roasbeef/subtrate/internal/api/grpc/subtraterpcb\x06proto3"

var (
	file_mail_proto_rawDescOnce sync.Once
	file_mail_proto_rawDescData []byte
)

func file_mail_proto_rawDescGZIP() []byte {
	file_mail_proto_rawDescOnce.Do(func() {
		file_mail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mail_proto_rawDesc), len(file_mail_proto_rawDesc)))
	})
	return file_mail_proto_rawDescData
}

var file_mail_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_mail_proto_msgTypes = make([]protoimpl.MessageInfo, 46)
var file_mail_proto_goTypes = []any{
	(Priority)(0),                      // 0: subtraterpc.Priority
	(MessageState)(0),                  // 1: subtraterpc.MessageState
	(*InboxMessage)(nil),               // 2: subtraterpc.InboxMessage
	(*SendMailRequest)(nil),            // 3: subtraterpc.SendMailRequest
	(*SendMailResponse)(nil),           // 4: subtraterpc.SendMailResponse
	(*FetchInboxRequest)(nil),          // 5: subtraterpc.FetchInboxRequest
	(*FetchInboxResponse)(nil),         // 6: subtraterpc.FetchInboxResponse
	(*ReadMessageRequest)(nil),         // 7: subtraterpc.ReadMessageRequest
	(*ReadMessageResponse)(nil),        // 8: subtraterpc.ReadMessageResponse
	(*ReadThreadRequest)(nil),          // 9: subtraterpc.ReadThreadRequest
	(*ReadThreadResponse)(nil),         // 10: subtraterpc.ReadThreadResponse
	(*UpdateStateRequest)(nil),         // 11: subtraterpc.UpdateStateRequest
	(*UpdateStateResponse)(nil),        // 12: subtraterpc.UpdateStateResponse
	(*AckMessageRequest)(nil),          // 13: subtraterpc.AckMessageRequest
	(*AckMessageResponse)(nil),         // 14: subtraterpc.AckMessageResponse
	(*GetStatusRequest)(nil),           // 15: subtraterpc.GetStatusRequest
	(*GetStatusResponse)(nil),          // 16: subtraterpc.GetStatusResponse
	(*PollChangesRequest)(nil),         // 17: subtraterpc.PollChangesRequest
	(*PollChangesResponse)(nil),        // 18: subtraterpc.PollChangesResponse
	(*SubscribeInboxRequest)(nil),      // 19: subtraterpc.SubscribeInboxRequest
	(*PublishRequest)(nil),             // 20: subtraterpc.PublishRequest
	(*PublishResponse)(nil),            // 21: subtraterpc.PublishResponse
	(*SubscribeRequest)(nil),           // 22: subtraterpc.SubscribeRequest
	(*SubscribeResponse)(nil),          // 23: subtraterpc.SubscribeResponse
	(*UnsubscribeRequest)(nil),         // 24: subtraterpc.UnsubscribeRequest
	(*UnsubscribeResponse)(nil),        // 25: subtraterpc.UnsubscribeResponse
	(*Topic)(nil),                      // 26: subtraterpc.Topic
	(*ListTopicsRequest)(nil),          // 27: subtraterpc.ListTopicsRequest
	(*ListTopicsResponse)(nil),         // 28: subtraterpc.ListTopicsResponse
	(*SearchRequest)(nil),              // 29: subtraterpc.SearchRequest
	(*SearchResponse)(nil),             // 30: subtraterpc.SearchResponse
	(*HasUnackedStatusToRequest)(nil),  // 31: subtraterpc.HasUnackedStatusToRequest
	(*HasUnackedStatusToResponse)(nil), // 32: subtraterpc.HasUnackedStatusToResponse
	(*RegisterAgentRequest)(nil),       // 33: subtraterpc.RegisterAgentRequest
	(*RegisterAgentResponse)(nil),      // 34: subtraterpc.RegisterAgentResponse
	(*GetAgentRequest)(nil),            // 35: subtraterpc.GetAgentRequest
	(*GetAgentResponse)(nil),           // 36: subtraterpc.GetAgentResponse
	(*ListAgentsRequest)(nil),          // 37: subtraterpc.ListAgentsRequest
	(*ListAgentsResponse)(nil),         // 38: subtraterpc.ListAgentsResponse
	(*EnsureIdentityRequest)(nil),      // 39: subtraterpc.EnsureIdentityRequest
	(*EnsureIdentityResponse)(nil),     // 40: subtraterpc.EnsureIdentityResponse
	(*SaveIdentityRequest)(nil),        // 41: subtraterpc.SaveIdentityRequest
	(*SaveIdentityResponse)(nil),       // 42: subtraterpc.SaveIdentityResponse
	(*DeleteAgentRequest)(nil),         // 43: subtraterpc.DeleteAgentRequest
	(*DeleteAgentResponse)(nil),        // 44: subtraterpc.DeleteAgentResponse
	nil,                                // 45: subtraterpc.PollChangesRequest.SinceOffsetsEntry
	nil,                                // 46: subtraterpc.PollChangesResponse.NewOffsetsEntry
	nil,                                // 47: subtraterpc.SaveIdentityRequest.ConsumerOffsetsEntry
}
var file_mail_proto_depIdxs = []int32{
	0,  // 0: subtraterpc.InboxMessage.priority:type_name -> subtraterpc.Priority
	1,  // 1: subtraterpc.InboxMessage.state:type_name -> subtraterpc.MessageState
	0,  // 2: subtraterpc.SendMailRequest.priority:type_name -> subtraterpc.Priority
	1,  // 3: subtraterpc.FetchInboxRequest.state_filter:type_name -> subtraterpc.MessageState
	2,  // 4: subtraterpc.FetchInboxResponse.messages:type_name -> subtraterpc.InboxMessage
	2,  // 5: subtraterpc.ReadMessageResponse.message:type_name -> subtraterpc.InboxMessage
	2,  // 6: subtraterpc.ReadThreadResponse.messages:type_name -> subtraterpc.InboxMessage
	1,  // 7: subtraterpc.UpdateStateRequest.new_state:type_name -> subtraterpc.MessageState
	45, // 8: subtraterpc.PollChangesRequest.since_offsets:type_name -> subtraterpc.PollChangesRequest.SinceOffsetsEntry
	2,  // 9: subtraterpc.PollChangesResponse.new_messages:type_name -> subtraterpc.InboxMessage
	46, // 10: subtraterpc.PollChangesResponse.new_offsets:type_name -> subtraterpc.PollChangesResponse.NewOffsetsEntry
	0,  // 11: subtraterpc.PublishRequest.priority:type_name -> subtraterpc.Priority
	26, // 12: subtraterpc.ListTopicsResponse.topics:type_name -> subtraterpc.Topic
	2,  // 13: subtraterpc.SearchResponse.results:type_name -> subtraterpc.InboxMessage
	36, // 14: subtraterpc.ListAgentsResponse.agents:type_name -> subtraterpc.GetAgentResponse
	47, // 15: subtraterpc.SaveIdentityRequest.consumer_offsets:type_name -> subtraterpc.SaveIdentityRequest.ConsumerOffsetsEntry
	3,  // 16: subtraterpc.Mail.SendMail:input_type -> subtraterpc.SendMailRequest
	5,  // 17: subtraterpc.Mail.FetchInbox:input_type -> subtraterpc.FetchInboxRequest
	7,  // 18: subtraterpc.Mail.ReadMessage:input_type -> subtraterpc.ReadMessageRequest
	9,  // 19: subtraterpc.Mail.ReadThread:input_type -> subtraterpc.ReadThreadRequest
	11, // 20: subtraterpc.Mail.UpdateState:input_type -> subtraterpc.UpdateStateRequest
	13, // 21: subtraterpc.Mail.AckMessage:input_type -> subtraterpc.AckMessageRequest
	15, // 22: subtraterpc.Mail.GetStatus:input_type -> subtraterpc.GetStatusRequest
	17, // 23: subtraterpc.Mail.PollChanges:input_type -> subtraterpc.PollChangesRequest
	19, // 24: subtraterpc.Mail.SubscribeInbox:input_type -> subtraterpc.SubscribeInboxRequest
	20, // 25: subtraterpc.Mail.Publish:input_type -> subtraterpc.PublishRequest
	22, // 26: subtraterpc.Mail.Subscribe:input_type -> subtraterpc.SubscribeRequest
	24, // 27: subtraterpc.Mail.Unsubscribe:input_type -> subtraterpc.UnsubscribeRequest
	27, // 28: subtraterpc.Mail.ListTopics:input_type -> subtraterpc.ListTopicsRequest
	29, // 29: subtraterpc.Mail.Search:input_type -> subtraterpc.SearchRequest
	31, // 30: subtraterpc.Mail.HasUnackedStatusTo:input_type -> subtraterpc.HasUnackedStatusToRequest
	33, // 31: subtraterpc.Agent.RegisterAgent:input_type -> subtraterpc.RegisterAgentRequest
	35, // 32: subtraterpc.Agent.GetAgent:input_type -> subtraterpc.GetAgentRequest
	37, // 33: subtraterpc.Agent.ListAgents:input_type -> subtraterpc.ListAgentsRequest
	43, // 34: subtraterpc.Agent.DeleteAgent:input_type -> subtraterpc.DeleteAgentRequest
	39, // 35: subtraterpc.Agent.EnsureIdentity:input_type -> subtraterpc.EnsureIdentityRequest
	41, // 36: subtraterpc.Agent.SaveIdentity:input_type -> subtraterpc.SaveIdentityRequest
	4,  // 37: subtraterpc.Mail.SendMail:output_type -> subtraterpc.SendMailResponse
	6,  // 38: subtraterpc.Mail.FetchInbox:output_type -> subtraterpc.FetchInboxResponse
	8,  // 39: subtraterpc.Mail.ReadMessage:output_type -> subtraterpc.ReadMessageResponse
	10, // 40: subtraterpc.Mail.ReadThread:output_type -> subtraterpc.ReadThreadResponse
	12, // 41: subtraterpc.Mail.UpdateState:output_type -> subtraterpc.UpdateStateResponse
	14, // 42: subtraterpc.Mail.AckMessage:output_type -> subtraterpc.AckMessageResponse
	16, // 43: subtraterpc.Mail.GetStatus:output_type -> subtraterpc.GetStatusResponse
	18, // 44: subtraterpc.Mail.PollChanges:output_type -> subtraterpc.PollChangesResponse
	2,  // 45: subtraterpc.Mail.SubscribeInbox:output_type -> subtraterpc.InboxMessage
	21, // 46: subtraterpc.Mail.Publish:output_type -> subtraterpc.PublishResponse
	23, // 47: subtraterpc.Mail.Subscribe:output_type -> subtraterpc.SubscribeResponse
	25, // 48: subtraterpc.Mail.Unsubscribe:output_type -> subtraterpc.UnsubscribeResponse
	28, // 49: subtraterpc.Mail.ListTopics:output_type -> subtraterpc.ListTopicsResponse
	30, // 50: subtraterpc.Mail.Search:output_type -> subtraterpc.SearchResponse
	32, // 51: subtraterpc.Mail.HasUnackedStatusTo:output_type -> subtraterpc.HasUnackedStatusToResponse
	34, // 52: subtraterpc.Agent.RegisterAgent:output_type -> subtraterpc.RegisterAgentResponse
	36, // 53: subtraterpc.Agent.GetAgent:output_type -> subtraterpc.GetAgentResponse
	38, // 54: subtraterpc.Agent.ListAgents:output_type -> subtraterpc.ListAgentsResponse
	44, // 55: subtraterpc.Agent.DeleteAgent:output_type -> subtraterpc.DeleteAgentResponse
	40, // 56: subtraterpc.Agent.EnsureIdentity:output_type -> subtraterpc.EnsureIdentityResponse
	42, // 57: subtraterpc.Agent.SaveIdentity:output_type -> subtraterpc.SaveIdentityResponse
	37, // [37:58] is the sub-list for method output_type
	16, // [16:37] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_mail_proto_init() }
func file_mail_proto_init() {
	if File_mail_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mail_proto_rawDesc), len(file_mail_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   46,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_mail_proto_goTypes,
		DependencyIndexes: file_mail_proto_depIdxs,
		EnumInfos:         file_mail_proto_enumTypes,
		MessageInfos:      file_mail_proto_msgTypes,
	}.Build()
	File_mail_proto = out.File
	file_mail_proto_goTypes = nil
	file_mail_proto_depIdxs = nil
}
